### ISSUE TITLE
"Max Length" property value is no longer saved into diagram file after update to 1.3.0.6

### ISSUE THREAD

**Issue by mmarinchenko** [msawczyn/EFDesigner#103]
I've just updated EF Designer from version 1.3.0.4 to 1.3.0.6. After that I've opened my test diagram and re-saved it. Max Length constraint disappeared.

Then I tried to set Max Length constraint in Properties window and saved diagram one more time. No luck.

So I opened diagram file in text editor. No Max Length value inside.

I use VS 2017 (15.9.16).

**Comment by msawczyn** [comment]
Thanks for the catch. Been working on a feature change for string length, where you can explicitly state that the string should be maximum available length, to remove the annoyances of getting a warning for 0-length string. That code got merged before it was ready.

It's yanked out now and the fix is in 1.3.0.7.

**Comment by mmarinchenko** [comment]
Many thanks for quick response, Michael!

**Comment by msawczyn** [comment]
v1.3.0.7 is now in the Releases section here on GitHub. Please let me know if you still experience any problems with this.

**Comment by mmarinchenko** [comment]
Ok, thank you! I'll try new version next week.

**Comment by mmarinchenko** [comment]
I've just installed v1.3.0.7 (over v1.3.0.4) and tested it with my diagram.

The only thing I found not very convenient is change in default AutoProperty value. To keep the previous behavior I had to go through all the properties and manually change the value to "True".

Everything else seems to be working fine. Thank you!

**Comment by msawczyn** [comment]
Hmm. Thanks. You should not have had to do that - it should be the default. I'll make sure to check that out and fix if it got flipped for some reason.

I appreciate you're testing it out.

**Comment by mmarinchenko** [comment]
As far as I understand the original diagram files (saved in v1.3.0.4) didn't have explicit autoProperty attributes in properties configuration.

So while reading XML (in v1.3.0.7) the absense of attributes were treated as they have "False" values. Therefore in the UI the values were set to False but bolded because on the UI layer the default is "True".

**Comment by msawczyn** [comment]
Yes, but they have a default 'true' value that's being set but then stepped
on by the modeling sdk framework. Most odd. I've started digging into this
already.

**Comment by mmarinchenko** [comment]
Thank you for your prompt support, Michael.

**Comment by msawczyn** [comment]
Fix available for review in [v1.3.0.8-pre](https://github.com/msawczyn/EFDesigner/releases/tag/v1.3.0.8-pre)
