### ISSUE TITLE
NotMapped Attribute support

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#105]
It might be useful to exclude some entities from DbContext configuration. Using the NotMapped Attribute is a very common way. By Design the Custom Attributes only will be generated as they are defined in the entity's property value.
For testing purposes i excluded those models it in the EFCoreDesigner.ttinclude file (DbSet generation => ~Line 161 and OnModelCreating generation => ~ line 268)

Seems to work quite well. The background for this adaption was, that I'm using a "NotMapped" Entity as a base class which provides some properties an navigations which will be reused by some inherited entities. Due to the issue that only TPH is implemented in EF Core. So I use this as workaround to get some compareable Inheritance to TPT or TPC.

**Comment by msawczyn** [comment]
Thanks for the suggestion. I'll put this on the enhancement list. 

Note that another approach you can currently use is to add the non-persistent base class in a  partial class, but it won't appear on the design surface.

**Comment by ANM86** [comment]
Yes that is absolutely true. I'm using your solution on many entity since a while. But it may have an visual disadvantage - as mentioned in #80 - if the base class includes the identity column it will generate entries in the error list, for each derrived entity, that the primary key column is missing. So if the base class has a quite simple structure i think inheritance by a partial class is the best solution. If the model gets more compley (several navigation etc.) then i think it makes more sense to have it in the design surface. That's the the reason why I'm using the DataAnnotation for some entities.

**Comment by msawczyn** [comment]
Due to the complexities of code generation, and the numerous edge cases, we've decided not to implement transient classes in the designer. That would also make it stray from its purpose as an EF modeling tool more toward a general-purpose class designer, and thereabouts fuzz the scope and intent of the tool. 

The alternative what you're wanting to do would be to use table-per-concrete-class inheritance and add the base class as an abstract class. 

Thanks for your input.

**Comment by ANM86** [comment]
Thank you for your response. As I am using mainly EF Core I'm afraid that TPC still is not available for it. In that case I will handle it with a change in the code of the ttincludes.
