### ISSUE TITLE
Cannot copy-paste property in the designer

### ISSUE THREAD

**Issue by RuiAlias** [msawczyn/EFDesigner#106]
Hi, I'm getting a `Object reference not set to an instance of an object` error when I try to copy-paste a property from some entity to another entity in the designer.

Let me know if you can't reproduce this error.

**Comment by msawczyn** [comment]
Can't reproduce. Am using the most current codebase (the soon-to-be-released v1.3.0.8)

**Comment by msawczyn** [comment]
Closed due to lack of activity

**Comment by RuiAlias** [comment]
I no longer have this issue in v1.3.0.8 pre-2. Thanks!
