### ISSUE TITLE
Many to many relationship support again

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#107]
Since many to many is still not naively supported in EF core and the question is if it is going to be soon(when I say implemented, I mean that junction table is not generated automatically), how can I implement that behavior by using designer? 
I have read all issues related to the topic, and I agree that it is not object modeling, and I realize why it is not implemented in designer.
According to this, I could implement it by creating appropriate tables in designer and implementing appropriate fluent API: https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration
Again, since fluent API is generated by the tool, it puts underscore on the foreign keys: https://github.com/msawczyn/EFDesigner/issues/15
So, since I can not change fluent API because it will be overwritten by tool, how can I create many to many entities.

**Comment by mciprijanovic** [comment]
I will try to answer to myself based on tests and provide some comments if useful to others looking for the same solution.
Lets look at the model with 2 entities A and B. So, aggregate entity could be created in designer as AB. Composite primary key must contain fields A_Id and B_Id. This way fluent api generated by designer generates foreign keys as it should. Key is marked as identity manual. Drawback is that when inserting aggregate item, AB constructor requires A_Id and B_Id.
So, maybe the best solution is that aggregate entity AB has one primary key as id auto generated and A_Id and B_Id just as foreign keys. This way the constructor will just require objects A and B, but not ids.
If someone has more intuitive solution, it would be nice to hear it. If not, sorry for reporting an issue and polluting the thread.
Anyway, congrats for the tool. It is very useful.

**Comment by msawczyn** [comment]
Thanks for your contribution! There are also a lot of writeups on the web about this:

- [Configuring Many To Many Relationships in Entity Framework Core](https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration)
- [Configure Many-to-Many Relationships in Entity Framework Core](https://www.entityframeworktutorial.net/efcore/configure-many-to-many-relationship-in-ef-core.aspx)
- [Relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)
- [Many-to-many relationships in EF Core 2.0 – Part 1: The basics](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/)

among others.
