### ISSUE TITLE
Drag and Drop on Designer gives error

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#112]
Dragging a simple file from Explorer to designer surface throws error.

File contents:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
	public class Example
	{
		public int Bar { get; set; }
	}
}
```

Error:
**Method not found: 'Microsoft.CodeAnalysis.SyntaxTree...**
See attached .jpg.
![EFDesignerDragDropError](https://user-images.githubusercontent.com/392415/67243566-b5e55000-f40c-11e9-914e-b120fdaef13f.JPG)

**Comment by msawczyn** [comment]
Fix available for review in [v1.3.0.8-pre](https://github.com/msawczyn/EFDesigner/releases/tag/v1.3.0.8-pre)

**Comment by dcastenholz** [comment]
No joy.  Verified 1.3.0.8 installed.  Same error dropping it on an empty designer.

**Comment by msawczyn** [comment]
Oh, this is most odd. I'll take another look. There's a dependency you don't have.

**Comment by dcastenholz** [comment]
thx

**Comment by msawczyn** [comment]
Is it possible that you don't have Roslyn in your Visual Studio installation?

**Comment by msawczyn** [comment]
Interesting stuff. The Nuget packages that the project use have deviated enough from what Visual Studio uses that they've become an issue. Couple that with the fact that the new "package reference" format (as opposed to using a `packages.config`) doesn't _necessarily_ copy the files into the VSIX. Luckily there's [a way to work around this](http://www.cazzulino.com/include-dlls-in-vsix.html), and I've given it a shot with [1.3.0.8-pre3](https://github.com/msawczyn/EFDesigner/releases/tag/v1.3.0.8-pre3).

If you can take a look to see if it resolves this problem, I'd be in your debt.

**Comment by dcastenholz** [comment]
Sorry for the slow response.  VS 2017 (15.9.17).  Installed 1.3.0.10 and I have a new error.
![EFDesigner DragDrop2](https://user-images.githubusercontent.com/392415/68720106-090d7700-0563-11ea-91e8-7230b28ac215.JPG)

**Comment by msawczyn** [comment]
There's something odd with your environment. While the extension does have a dependency on System.Memory, it's indirect. And that particular version isn't called for anywhere -- it's too low. Can you try uninstalling and reinstalling, rather than upgrading? May not do anything, but worth a shot. I have it installed in VS2017 as well -- in fact, it's compiled using VS2017 -- and haven't seen the kinds of issues you've been experiencing.

Thanks for the report. Looking forward to hearing the results.

**Comment by dcastenholz** [comment]
This behavior is exhibited on 2 different machines.  I uninstalled and reinstalled on one of them.  No change in behavior.

Thank you,

Daniel

Daniel Castenholz – Senior Software Engineer
San Luis Obispo County Sheriff's Office
Phone: 805.781.4504

[SheriffPatch]

**Comment by msawczyn** [comment]
Can you tell me exactly what you were doing when the error popped up?

**Comment by dcastenholz** [comment]
Dragged the previously attached .cs file from the solution explorer onto the model surface and dropped it.
