### ISSUE TITLE
Nullref errors in tool

### ISSUE THREAD

**Issue by bjoholen** [msawczyn/EFDesigner#113]
Version 1.3.0.7 handles drag and drop of files. However, when trying this i wanted to undo the drop and did ctrl-z. The change disappeared but was followed by this;
![image](https://user-images.githubusercontent.com/13807891/67385921-4f8b3980-f594-11e9-995a-08eb6a87b48c.png)

**Comment by msawczyn** [comment]
Fix available for review in [v1.3.0.8-pre](https://github.com/msawczyn/EFDesigner/releases/tag/v1.3.0.8-pre)
