### ISSUE TITLE
"Object reference not set..." error on drag and drop of existing code.

### ISSUE THREAD

**Issue by michaelpear** [msawczyn/EFDesigner#114]
I'm trying to generate a diagram/model from files output from the Scaffold-DB, but getting the dreaded "Object reference not set to an instance of an object" when I drag any one of the files to the diagram surface.  I'm using Visual Studio 2019 V16.3.6 with V1.3.0.6

 I am able to create entities from the toolbox, but am getting the error on a file as simple as:

`
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace TrainingManagerSchema.Reverse
{
   public partial class EntityMinimal
   {
       [Key]
      [Required]
      public int Id { get; private set; }
      public string Test { get; set; }
   }
}`

I see issue #112 reports a drag and drop error, but is reported differently and there is no indication of the version of VS or the extension.

**Comment by msawczyn** [comment]
Fix available for review in [v1.3.0.8-pre](https://github.com/msawczyn/EFDesigner/releases/tag/v1.3.0.8-pre)
