### ISSUE TITLE
Identity properties ignore Setter Visibility setting

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#118]
It looks like the set accessor of an entity's primary key is labeled "private" even when the corresponding Property "Setter Visibility" is set to "Public".

**Comment by msawczyn** [comment]
Thanks. SetterVisibility shouldn't be available for identity properties with generated properties; that change is now in place. Manual properties now obey the setter visibility.

**Comment by alprinias** [comment]
Dear Michael, unfortunately, with version 1.3.0.10, my string manual identity columns keep getting generated with private setters, although the properties window shows public.
