### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by ddewaleffe** [msawczyn/EFDesigner#12]
Was trying to define a recursive relation.  one-to-many from T to T.
When I validate I get no issue but on db creation I get exception saying I should add ON CASCADE DELETE NOACTION...

Looks like the code options on the relation in the editor does something when set to CASCADE but nothing when set to NONE. [EF6] Which IMHO should be the reverse since EF6 cascades by default. Or the generated code should always add a WillCascadeOn() call with true/false without relying on the default.

I do not know the defaults for EF Core..

Setting the relation ends to CASCADE, then passing false , in place of nothing, into generated code allows the db to be created.  Am I doing something wrong or missig something?

Version: 1.2.2.1

And kudos for such a nice tool.

Thanks,
D.

**Comment by msawczyn** [comment]
I've seen what you're describing myself, and in those cases it's been more of an issue of the design of the model itself creating multiple cascade paths, which SQL Server doesn't allow. That's quite common in models with self-referencing classes; what's likely happening is that you have another association to that class that triggers a cascade delete (say, another 1..n or a 0/1..1). SQL Server sees that it's possible that cascade delete sweeps can cause an already-deleted record to need to be deleted again, and it doesn't like that.

It's an annoying problem that forces you to remember that the database exists when you're doing the object modeling ... and in a perfect world, your modeling tasks should be completely separated from troublesome details like how your objects are being persisted. There is a way of avoiding the whole mess (most of the time), and I have an item on the [todo list](https://github.com/msawczyn/EFDesigner/blob/master/TODO.txt) to add an enhanced cascade delete option; it would generate code that migrates to database triggers, sidestepping the problem.

That being said, I can see that I didn't devote as much attention to the whole cascade delete tooling as I should have. The _None_ setting really means "do the default thing" (i.e., don't generate any code to guide the behavior), whereas _Cascade_ forces the issue. There really should be three choices: _None_, _Cascade_, and _Default_. Right now, _None_ is really _Default_ (why in the world did I think that was a good word choice?) and I need to make that change.

Seem like a good approach to you?

And thanks for the kind words. Feel free to vote up on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner) (shameless grin).

**Comment by ddewaleffe** [comment]
Given I am ready to handle the issue in code, I would be ok with a third option that indeed really disables cascade... But that's just me....  D.

**Comment by msawczyn** [comment]
The fix for this will be in the next release, hopefully later tonight or tomorrow.

**Comment by msawczyn** [comment]
Fixed in v1.2.3
