### ISSUE TITLE
base class of entities without corresponding dbset

### ISSUE THREAD

**Issue by pas059** [msawczyn/EFDesigner#121]
Hello and thanks for this nice tool.

I'd like to create a base class of some entities but i don't want that this base class corresponds to a DbSet, and so to a table. Even by setting the base class as Abstract, a DBset line is generated. 
And secondly, is it possible to create such base class without Key, assuming that the Keys are in the derived classes.
In other words, is it possible to create a base class of entities rather to create an entity that acts as a base class of other entities?

Regards
Pascal

**Comment by pas059** [comment]
Hi again,

i found some solutions. Thanks to the good design of this tool, it is possible to modify the way the code is generated. For the 1st question, as i use EF core, i modified the file 'EFCoreDesigner.ttinclude' as explained in [https://msawczyn.github.io/EFDesigner/Customizing](url) . I just added in function 'WriteDbContextEFCore()' on line 174, this:
`         if ( dbSetName.Equals("NoDbSet") )
			continue;
` so that when the DbSet Name property of an entity is set to 'NoDbSet', no DbSet is generated.

For the second point, i modified the file 'EFDesigner.ttinclude' like this:
- in the function 'WritePersistentProperties' i changed the lines 718-726 by:
`      string setterVisibility = modelAttribute.ModelClass.ModelRoot.EntityFrameworkVersion == EFVersion.EFCore && modelAttribute.IsIdentity && !modelClass.IsAbstract ? "private " :
                                modelAttribute.SetterVisibility == SetterAccessModifier.Protected ? "protected " : 
                                modelAttribute.SetterVisibility == SetterAccessModifier.Internal ? "internal " : 
                                string.Empty;`
 `      GeneratePropertyAnnotations(modelAttribute, modelClass.IsAbstract);`
- the function 'GeneratePropertyAnnotations' becomes: `void GeneratePropertyAnnotations(ModelAttribute modelAttribute, bool ignoreIdentity )
{
   if (modelAttribute.IsIdentity && !ignoreIdentity)               Output("[Key]");
`
like this an abstract entity/class is generated without [Key] attribute on the correspondng property and the setter of the property remains public (not private).

Not sure that this is the best way to do this, nor this is a good practice, but this works.
Other thing, i think that this would be better if the constructors could be 'public' even if there are 'Required' properties; this ccould also be changes by modifying the files above, but i've let this like the origin.

Regards,
Pascal

**Comment by msawczyn** [comment]
Glad you were able to customize the code generation to your liking. There was some work done earlier to allow transient classes to be added to the designer for exactly the reason you were asking about, but it started the project drifting away from its original intent of being an EF designer as opposed to a general-purpose class design utility.

As mentioned in another question, another way to achieve what you're wanting to do is to add the base class in a partial class. No change to the T4 is needed for that.

**Comment by Tdue21** [comment]
I know this question is closed, but I was wondering what the referenced question is? 

> As mentioned in another question, another way to achieve what you're wanting to do is to add the base class in a partial class.

I would love to base all entities off a base class with a couple of common properties, but I'd prefer not to mess around with the T4 template. So, the method mentioned sounds intriguing, but I can't find the question in ... question ;)
