### ISSUE TITLE
Error while opening .efmodel file in VS 2017 after upgrade from v1.3.0.7 to v1.3.0.9

### ISSUE THREAD

**Issue by mmarinchenko** [msawczyn/EFDesigner#123]
I've tried v1.3.0.9. It seems some additional dependencies are required... VS 2019? :)

**Comment by mmarinchenko** [comment]
From ActivityLog.xml:

`  <entry>
    <record>2135</record>
    <time>2019/11/11 06:41:49.038</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [EFModelPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. &#x041D;&#x0435; &#x0443;&#x0434;&#x0430;&#x0435;&#x0442;&#x0441;&#x044F; &#x043D;&#x0430;&#x0439;&#x0442;&#x0438; &#x0443;&#x043A;&#x0430;&#x0437;&#x0430;&#x043D;&#x043D;&#x044B;&#x0439; &#x0444;&#x0430;&#x0439;&#x043B;.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. &#x041D;&#x0435; &#x0443;&#x0434;&#x0430;&#x0435;&#x0442;&#x0441;&#x044F; &#x043D;&#x0430;&#x0439;&#x0442;&#x0438; &#x0443;&#x043A;&#x0430;&#x0437;&#x0430;&#x043D;&#x043D;&#x044B;&#x0439; &#x0444;&#x0430;&#x0439;&#x043B;.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;&#x041F;&#x0440;&#x0435;&#x0434;&#x0443;&#x043F;&#x0440;&#x0435;&#x0436;&#x0434;&#x0435;&#x043D;&#x0438;&#x0435;: &#x0440;&#x0435;&#x0433;&#x0438;&#x0441;&#x0442;&#x0440;&#x0430;&#x0446;&#x0438;&#x044F; &#x043F;&#x0440;&#x0438;&#x0432;&#x044F;&#x0437;&#x043A;&#x0438; &#x0441;&#x0431;&#x043E;&#x0440;&#x043E;&#x043A; &#x0432;&#x044B;&#x043A;&#x043B;&#x044E;&#x0447;&#x0435;&#x043D;&#x0430;.&#x000D;&#x000A;&#x0427;&#x0442;&#x043E;&#x0431;&#x044B; &#x0432;&#x043A;&#x043B;&#x044E;&#x0447;&#x0438;&#x0442;&#x044C; &#x0440;&#x0435;&#x0433;&#x0438;&#x0441;&#x0442;&#x0440;&#x0430;&#x0446;&#x0438;&#x044E; &#x043E;&#x0448;&#x0438;&#x0431;&#x043E;&#x043A; &#x043F;&#x0440;&#x0438;&#x0432;&#x044F;&#x0437;&#x043A;&#x0438; &#x0441;&#x0431;&#x043E;&#x0440;&#x043E;&#x043A;, &#x0443;&#x0441;&#x0442;&#x0430;&#x043D;&#x043E;&#x0432;&#x0438;&#x0442;&#x0435; &#x0437;&#x043D;&#x0430;&#x0447;&#x0435;&#x043D;&#x0438;&#x0435; &#x043F;&#x0430;&#x0440;&#x0430;&#x043C;&#x0435;&#x0442;&#x0440;&#x0430; &#x0440;&#x0435;&#x0435;&#x0441;&#x0442;&#x0440;&#x0430; [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) &#x0432; 1.&#x000D;&#x000A;&#x041F;&#x0440;&#x0438;&#x043C;&#x0435;&#x0447;&#x0430;&#x043D;&#x0438;&#x0435;. &#x0420;&#x0435;&#x0433;&#x0438;&#x0441;&#x0442;&#x0440;&#x0430;&#x0446;&#x0438;&#x044F; &#x043E;&#x0448;&#x0438;&#x0431;&#x043E;&#x043A; &#x043F;&#x0440;&#x0438;&#x0432;&#x044F;&#x0437;&#x043A;&#x0438; &#x0441;&#x0431;&#x043E;&#x0440;&#x043E;&#x043A; &#x043C;&#x043E;&#x0436;&#x0435;&#x0442; &#x043F;&#x0440;&#x0438;&#x0432;&#x0435;&#x0441;&#x0442;&#x0438; &#x043A; &#x043D;&#x0435;&#x043A;&#x043E;&#x0442;&#x043E;&#x0440;&#x043E;&#x043C;&#x0443; &#x0441;&#x043D;&#x0438;&#x0436;&#x0435;&#x043D;&#x0438;&#x044E; &#x043F;&#x0440;&#x043E;&#x0438;&#x0437;&#x0432;&#x043E;&#x0434;&#x0438;&#x0442;&#x0435;&#x043B;&#x044C;&#x043D;&#x043E;&#x0441;&#x0442;&#x0438;.&#x000D;&#x000A;&#x0427;&#x0442;&#x043E;&#x0431;&#x044B; &#x043E;&#x0442;&#x043A;&#x043B;&#x044E;&#x0447;&#x0438;&#x0442;&#x044C; &#x044D;&#x0442;&#x0443; &#x0444;&#x0443;&#x043D;&#x043A;&#x0446;&#x0438;&#x044E;, &#x0443;&#x0434;&#x0430;&#x043B;&#x0438;&#x0442;&#x0435; &#x043F;&#x0430;&#x0440;&#x0430;&#x043C;&#x0435;&#x0442;&#x0440; &#x0440;&#x0435;&#x0435;&#x0441;&#x0442;&#x0440;&#x0430; [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{56BBE1BA-AAEE-4883-848F-E3C8656F8DB2}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
`

**Comment by mmarinchenko** [comment]
![Dialog](https://user-images.githubusercontent.com/21952330/68567101-fb2ff700-0479-11ea-944d-06fa8bac425b.png)
![Warning](https://user-images.githubusercontent.com/21952330/68567102-fbc88d80-0479-11ea-951f-73cc2713da26.png)

**Comment by mmarinchenko** [comment]
I've reverted to v1.3.0.7 for now. Everything works again.

**Comment by msawczyn** [comment]
Grr. It was a bonehead mistake on my part. Sorry. 1.3.0.10 is being posted with the corrected build configurations. Sorry!

**Comment by mmarinchenko** [comment]
Oh, I see...

I downloaded v1.3.0.10. It's working!
Awesome release, Michael. Thank you for the great work!
