### ISSUE TITLE
Layout Algorithm Settings documentation question

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#124]
Just wondering if there is documentation on the 'Layout Algorithm Settings' property for the designer.  I am building a conversion app for some of our old XML based apps.  The one I am working on has over 200 tables, so manual layout is a bit of a pain.  I am looking to make the spacing between the classes smaller in both the vertical and the horizontal.  Thanks.

**Comment by msawczyn** [comment]
That feature uses by [Microsoft Automatic Graph Layout](https://github.com/microsoft/automatic-graph-layout). While the documentation does need updated to talk about that bit, I don't plan to go into much detail about how to configure, instead pointing to the existing docs on the 'net that discuss that project.

Plugging that into the designer was quite eye-opening, as there is a whole science around this that I haven't looked at in detail. So the designer docs are going to fall back to the ubiquitous "details are out of scope for this document" and just punt the problem back to Microsoft Research :-)

**Comment by dcastenholz** [comment]
Good enough.  I will dive into the MS docs.
Thanks.
