### ISSUE TITLE
Default constructor visibility

### ISSUE THREAD

**Issue by Diego66** [msawczyn/EFDesigner#125]
ASP.NET Core MVC 3.0 ModelBinding error when posting to controller: 
System.InvalidOperationException: Could not create an instance of type 'My.Models.MyEntity'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.
MyEntity doesn't have a public parameterless constructor because some properties are non-nullable.

**Comment by msawczyn** [comment]
Can you please provide a simple model file that shows the problem? I'm not quite sure I understand how you got that.

**Comment by Diego66** [comment]
The model generated has a protected default constructor, because one or more properties are required. That's what breaks model binding in ASP.NET MVC.
From Microsoft documentation:

> Complex types
> A complex type must have a public default constructor and public writable properties to bind. When model binding occurs, the class is instantiated using the public default constructor.

**Comment by RuiPaivaSier** [comment]
I guess you can change the EFDesigner.ttinclude file (https://msawczyn.github.io/EFDesigner/Customizing.html), and change the line that set the visibility (for me is line 434) of the constructor. But it kind of breaks the purpose of having constructors with parameters... be aware that the id has a "private set", which you may want to modify as well... do it at your own risk. But I understand that it makes it much easier to scaffold MVC Controllers with views, using Entity Framework.

**Comment by msawczyn** [comment]
The "best practices" approach for this is _not_ to send the entities into the views; rather, you'll want to create a data-transfer object (DTO) that contains the data the view needs, let that get modified (if necessary) by the view and then send it back for processing.

The persistent entities should model reality, and the views may or may not be presenting _exactly_ that data to the user. The DTOs' purpose is to serve the data the views need - their transient vehicles used to communicate the data between the server (where the persistent entities exist) and the user interface.

The constructors' generated code (as well as other code created by the templates) is designed to create a "pit of success" where doing the right thing is the same as doing the easiest thing. Any constructor that's not generated can, of course, be easily added in the partial class.
