### ISSUE TITLE
Generate code fails in sdk project

### ISSUE THREAD

**Issue by VioletS** [msawczyn/EFDesigner#127]
I have a project that has used your great tool before.
Recently,  this projects was migrates to an sdk project that, among others, targets netstandard2.0.
After this change, I can no longer generate code: it claims my .tt file was updated, but my entities remain unchanged.

I have tested this with your latest release, 1.3.0.11

Used csproj after change (irrelevant details redacted):

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>my.super.awesome.package</PackageId>
    <Description>Descriptive description.</Description>
    <PackageProjectUrl>fictional.addres/projectpage</PackageProjectUrl>
    <PackageTags>Are These Relevant</PackageTags>
    <CodeAnalysisRuleSet>my.super.awesome.package.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <my PackageReferences />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Datamodel\Datamodel.csproj" />
  </ItemGroup>
</Project>
`

**Comment by VioletS** [comment]
_I don't know if this is at all related to your tool, but another console tool broke in the same migration. For this, the fix was to set a dummy application as a startup project. However, this does not help with EFDesigner.
https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#other-target-frameworks_

**Comment by msawczyn** [comment]
Yes, SDK projects and T4 template code generation doesn't (didn't?) work well. It's been a while since I've looked at the problem, so maybe it's evolved. It's definitely on the list of things to do.

**Comment by mmarinchenko** [comment]
My EFCore SDK-based project file looks like this (attached). Feel free to use it as a reference (I removed private data from it).

In the project root directory I have the following files:
- DataModel.cs (empty)
- DataModel.csproj (attached)
- DataModel.efmodel
- DataModel.efmodel.diagram
- DataModel.tt

[DataModel.txt](https://github.com/msawczyn/EFDesigner/files/3916756/DataModel.txt)

**Comment by msawczyn** [comment]
Thanks for that. It proved quite interesting. Confusing, but interesting. Here's what I did:

1. Created an empty directory
2. Copied the above text file in as a csproj
3. Opened the csproj in Visual Studio v16.3.6
4. Copied the model files from the Github repository `\src\Testing\Testing_EFCoreV2NetCore` directory (`AllFeatureModel.efmodel`, `AllFeatureModel.efmodel.diagram`, and `AllFeatureModel.tt`). Renamed them to `DataModel`. This is my "kitchen sink" model that contains all sorts of permutations ... the best thing I could come up with for an integration test data set.
5. Edited the `.tt` file on line 17 to have it point to its model file's new name
```
#><#@ EFModel processor="EFModelDirectiveProcessor" requires="FileName='DataModel.efmodel'"  
```
6. Visual Studio picked up on the new files' existence, so I tried generating the `efmodel` file via its context menu command.

Results: the `Generated` directory and its subdirectories appeared in the project, and all the generated files appeared in the appropriate directory.

I'm attaching the solution and project files (VStudio, of course, created the solution automatically when I saved the project) for you both to try in your environments.

[DataModelTest.zip](https://github.com/msawczyn/EFDesigner/files/3937858/DataModelTest.zip)

**Comment by msawczyn** [comment]
@VioletS - 

I tried to do the same as above with the project data you posted in your first message, but VStudio had issues with it.
```
<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <PackageId>my.super.awesome.package</PackageId>
      <Description>Descriptive description.</Description>
      <PackageProjectUrl>fictional.addres/projectpage</PackageProjectUrl>
      <PackageTags>Are These Relevant</PackageTags>
      <CodeAnalysisRuleSet>my.super.awesome.package.ruleset</CodeAnalysisRuleSet>
   </PropertyGroup>
   <ItemGroup>
      <my PackageReferences />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Datamodel\Datamodel.csproj" />
   </ItemGroup>
</Project>
```

I had named the file VS_EFCore_NetStdV20.csproj, and the error was:
```
The project file could not be loaded. '/' is an unexpected token. The expected token is '='. Line 12, position 29.  C:\Code\EFDesigner\src\Testing\VS_EFCore_NetStdV20\VS_EFCore_NetStdV20.csproj
```
so I didn't want to go any farther with that without knowing what the package references really were.

**Comment by mmarinchenko** [comment]
@msawczyn

I downloaded your archive, unpacked it and deleted "Generated" folder. Then I opened solution using VS 2017, opened data model and generated code through context menu. All went fine.

**Comment by mmarinchenko** [comment]
@VioletS

1. I guess you posted here wrong project. You need to look at configuration of the project which contains *.efmodel files, not the one which uses it as a dependency. Datamodel.csproj ?

2. Please prepare a syntactically correct example (without `<my PackageReferences />` and such) and make sure the issue can be reproduced using this example..

**Comment by VioletS** [comment]
It turns out the migrated csproj was indeed missing some required code, which I could have found out if I had generated a new project. The confusion came from just tools complaining, when everything did build and run just fine. Sorry to waste your time, but thanks for the help!
