### ISSUE TITLE
Designer Drag/Drop Interpreter fails

### ISSUE THREAD

**Issue by SirBobcat** [msawczyn/EFDesigner#128]
Verified Drag to designer works with V1.3.0.7 but fails with 1.3.0.8 and later using VS 2019 Community.  Did not test intermediate releases of 1.3.0.8.

**Comment by msawczyn** [comment]
Please update to the latest version in the Marketplace (or here in Github), currently v1.3.0.11. Also ensure you're using Visual Studio 16.2.5 or later, since there was a bug prior to that that caused issues with mouse gestures in any Microsoft Modeling SDK project.

**Comment by SirBobcat** [comment]
Not sure how this response relates to the problem I described.

To reiterate:


  1.  Drag/Drop file works for V1.3.0.7
  2.  2. Does not work V1.3.0.8
  3.  3. Does not work V1.3.0.11


All results verified using VS2017 and VS 2019 Community editions.

Regards
