### ISSUE TITLE
Unique index not generated

### ISSUE THREAD

**Issue by ddewaleffe** [msawczyn/EFDesigner#13]
Wanted a unique index on a string column[25], so selected both Indexed and unique index to true.
Index is created but the unique info seems to be ignored.

D.

**Comment by msawczyn** [comment]
Found where the output was missing in the EF6 template and am adding that. 

Did you see this behavior in EFCore or EF6? If the former, that's a problem -- code to emit that is in EFCoreDesigner.ttinclude lines 276-292.

**Comment by ddewaleffe** [comment]
using ef6 at the moment...

D.

-----------------------------------------
Dominique de Waleffe
GSM:+32 477 533 521
dominique@4d-consult.com

**Comment by msawczyn** [comment]
Phew. Good. Then I fixed it.  Thanks for bringing it to my attention. Can't figure how I missed adding that.

It's [in github](https://github.com/msawczyn/EFDesigner/blob/master/src/DslPackage/TextTemplates/EF6Designer.ttinclude) now, and will be in the next release, as soon as I get some pull requests looked at and merged.

**Comment by msawczyn** [comment]
Fixed in v1.2.3
