### ISSUE TITLE
Entity property's "Column Name" and "Column Type" are set when a new property is added

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#131]
Hi,
I'm using version 1.3.0.10 with EF Core, and just notied that when I add a new property to any entity, I can see thiw new property's properties "Column Name" and "Column Type" to be set in the Properties VS Window. The respective values are the new property's name (by default Property1)  and "default". I could swear that this was not the case with earlier versions.

Is there a reason this changed? Do we need the names to be set for some reason?

Thank you. And sorry for all these "properties"!

**Comment by msawczyn** [comment]
No, the names don't need to be set (unless you want to change them from the defaults) but the defaults should indeed be showing. Don't know how that slipped past. Fixing for the .12 release.

Thanks!

**Comment by msawczyn** [comment]
Fixed in 1.3.0.12; column name and type entries no longer display as empty.

**Comment by alprinias** [comment]
Michael,

I don't know if this is related: I am still using the 1.3.10 version. I added a new entity with 2 properties, generated the code and did an Add-Migration. Instead of adding teh new entity, the migration had a myriad of alter column lines, each of them altering a string column of my old (existing before the new entity) tables. What each of these alter column lines is trying to change the column type from nvarchar(max) to the one really defined with the MaxLength, which was already defined and migrated to my db and working fine. The result is that the update database does not work, since it thinks that I'm altering columns which are participating in indices and foreign keys. 
Is it related with this? How does the Add-Migration work? Does it look at your model? Why does it think that the old column type was nvarchar(max) ? 
I'm very confused.
Alex

**Comment by msawczyn** [comment]
Hi Alex,

The add-migration script doesn't have any knowledge of the designer; it's looking at the class definitions and their entity framework mapping and deciding what to do. I've seen the Core version make some really bad decisions ... likely they're still working the bugs out on that.

**Comment by alprinias** [comment]
Hi Michael, thanks for your answer.
I'm really not sure what it had happened. It kind of fixed itself after removing the faulty migration, closing down VS, reponening and regenerating the migration. I'm confused, but it now works.
Thank you again. Wishing you all the best for the Christmas period and for the New Year!
Alex
