### ISSUE TITLE
Cannot Drag and Drop Onto Designer

### ISSUE THREAD

**Issue by MissyGH** [msawczyn/EFDesigner#132]
I'm using Entity Framework v 2.2.6 and Entity Framework Visual Editor v 1.3.0.11 on a NET Standard 2.0 application.   I really, really, really would love to use your tools because I can't find another visual editor for EF.   I'm using :

Microsoft Visual Studio Community 2019
Version 16.4.0

When I try to drag my classes on to the designer, I get the following error:

Error interpreting (my model name)

Please help!!!

**Comment by SirBobcat** [comment]
Same as #128

**Comment by msawczyn** [comment]
I think we have this fixed in the next version, but could both of you post a class that currently doesn't parse so I can have them for test data? I really want to be sure this thing is resolved. 😁

**Comment by MissyGH** [comment]
Here you go:

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayer.Models
{
    [Table("Address", Schema = "merchant")]
    public partial class MercAddress
    {
        [Column("CustomerIDID")]
        public int CustomerIDId { get; set; }
        [Column("AddressTypeID")]
        public int AddressTypeId { get; set; }
        [Required]
        [StringLength(255)]
        public string AddressName { get; set; }
        [Required]
        [StringLength(255)]
        public string AddressLine1 { get; set; }
        [Required]
        [StringLength(255)]
        public string AddressLine2 { get; set; }
        [Required]
        [StringLength(255)]
        public string City { get; set; }
        [Required]
        [StringLength(2)]
        public string State { get; set; }
        [Required]
        [StringLength(10)]
        public string Zip { get; set; }
        [Required]
        [StringLength(255)]
        public string Title { get; set; }
        [Required]
        [StringLength(255)]
        public string AddressPhone { get; set; }
        [Required]
        [StringLength(255)]
        public string AddressEmail { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateAdded { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTerminated { get; set; }
        [Column("AddressID")]
        public int AddressId { get; set; }

        [ForeignKey("AddressTypeId")]
        [InverseProperty("CustAddresses")]
        public virtual RefAddressType AddressType { get; set; }
        [ForeignKey("CustomerIDId")]
        [InverseProperty("CustAddresses")]
        public virtual CustApplication CustomerID { get; set; }
    }
}

**Comment by SirBobcat** [comment]
Here you go, nothing fancy.

Sir Bobcat

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
