### ISSUE TITLE
EFModel added to .NET Core class library generates EF6-related files

### ISSUE THREAD

**Issue by mmarinchenko** [msawczyn/EFDesigner#135]
Hi Michael!

I've made the following manual test with VS 2019 v16.4.2 + .NET Core SDK 3.1.100 + EFDesigner v1.3.0.12.

1. Create new SDK-style ASP.NET Core Web Application project (with new solution).
2. EFDesigner model can't be added to this type of projects, so I added Class Library (.NET Core) project to the solution.
3. Add EFDesigner model to Class Library (.NET Core) project through Add -> New Item context menu.
4. Add new entity to diagram surface.
5. Click Save All toolbar button (which toggle code generation).

After that I found EFModel1DatabaseInitializer.generated.cs and EFModel1DbMigrationConfiguration.generated.cs files which use EF6's System.Data.Entity namespace despite the fact that whole project is based on EF Core.

**Comment by mmarinchenko** [comment]
Archive attached [WebApplication1.zip](https://github.com/msawczyn/EFDesigner/files/4021858/WebApplication1.zip)

**Comment by msawczyn** [comment]
That model was set to generate EF6. It's a property on the design surface (`Entity Framework Version`). The tool never attempts to determine the type of project.

**Comment by mmarinchenko** [comment]
My bad.

Thanks for clarification!
