### ISSUE TITLE
DSL: Value converters support

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#138]
Is there a way (or in plan) to support value converters from designer? Here is the case I have and my solution for it without using designer.

I have custom type object in my entity that is stored as JSON serialized string in the db. I am using value converter to serialize and deserialize that object to and from storage. 

So, everything basically works and a few actions that should be performed are:
1. Create custom class for the property
2. Create entity partial class (part not overwritten by designer) and create property with custom type.
3. Create db context partial class (part not overwritten by designer) and add the part for custom property in OnModelCreating with value converter used.

Where is the drawback? Drawback is that custom property implemented in partial class for entity is not visible by designer, and it can't be added through designer since just basic types can be used or other entities from the designer. 
I guess that possible solution could be 
- to loose constraint of property type so that we can enter it in  the free form (beside the list), and to create custom type manually (which can probably cause bad behavior on some other side)
- or to add support for some entities within designer which are not neither persistent entities neither enums. 
- or type list to somehow recognize custom types created manually

If support for this already exists, I am sorry, I didn't find it.

**Comment by msawczyn** [comment]
Thanks for the suggestion. That's not in the plan yet, but I'll certainly add it to the backlog. If it's something that can be done in a way that's easy for the users and saves time and errors, it'll be a good addition.

**Comment by msawczyn** [comment]
@mciprijanovic - I looked into solutions for this while gathering up the bits for the 2.0 release. Can you please post (upload/link/etc) a sample of the solution you've devised to this problem so that I understand the problem better?

Thanks.

**Comment by mciprijanovic** [comment]
Michael, 

Sorry for the late answer, I was on the vacation. Here is the described case in order to understand problem better.
I have entity Equipment created in designer. Equipment model class is therefore automatically generated class. Now, I created a partial class with same name in order not to add code in generated class. Here is the class:

public partial class Equipment
    {        
        public List<Graph> ProductionGraphsSettings { get; set; }
    }

Graph object is not entity created from designer, it is a custom class. Now, I want list of Graph objects to be serialized to JSON and to be saved as a varchar field in db table Equipment. I managed to do this in a following way: I extended db context with partial class:

public partial class AdministrationDbContext
    {
        partial void OnModelCreatedImpl(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<global::Novolyze.Administration.Model.Equipment>()
                     .Property(t => t.ProductionGraphsSettings)
                     .HasConversion(new ModelToJsonConverter<List<Graph>>());
        }
    }

So, scenario is achievable, the question is just if it can be easier achievable just by using designer with no need to create partial classes. 

If anything else needed, please write.

**Comment by msawczyn** [comment]
https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions

**Comment by msawczyn** [comment]
Been looking at this one and it appears to have so many possible variations that the designer really can't offer any help. The solution you've come up with (configuring the value converter in the partial method) is indeed the best way to go and really the reason the partials are there ... to cover the cases where the tool just can't be of any help.

I'm going to close this now as a "won't do" but, if you come up with some way the designer can help that I haven't thought of, please feel free to reopen and comment.
