### ISSUE TITLE
Auto sizing Entities on .efmodel

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner#151]
Hi Michael,

Is there a setting that auto sets width of the entities on the .efmodel diagram pane to fit the longest content information per entity member/attribute?

Thank you

**Comment by msawczyn** [comment]
Unfortunately, no. You can put that in as an enhancement request, though. 

The default width of the element is calculated by code in the Microsoft Modeling SDK and, although there are a _huge_ number of extension points, that isn't one I've seen. Doesn't mean it can't be done, but it would take some research.
