### ISSUE TITLE
Create multiple diagrams (views) over the same model

### ISSUE THREAD

**Issue by msawczyn** [msawczyn/EFDesigner#153]

**Comment by dcastenholz** [comment]
This is a fantastic feature, by the way.  This alone is making me consider moving a large project to VS2019.  Thanks!

**Comment by msawczyn** [comment]
Thanks! Once I get the last of the bugs out I'll be quite proud of it. To my knowledge, having multiple diagrams, in this manner, is the Holy Grail of the Visual Studio Modeling SDK  ... there's some support for it in the SDK, but it's never been fully implemented, and some of the SDK's foundation needed to be enhanced to make it possible. I've not seen anyone do this yet, so if I can get it solid and performant, it'll be breaking new ground.

Unless I'm mistaken, of course, and all the hard preliminary work was wasted when I could have just seen how someone else did it, but I've been looking for 12 years now :-)
