### ISSUE TITLE
Question about many-to-many

### ISSUE THREAD

**Issue by ceeroshelter** [msawczyn/EFDesigner#155]
Hey

I'm currently evaluating wether to use EF Core or XPO for a project I'm working on, and one of the factors atm is how easily I can set up many-to-many associations.

The regular code-first in EF Core seems to result in a lot of code bloat, but I came over your very promising project and figured I'd give that a look.

Here I've just set up two entities with bidirectional many-to-many association directly between them to see which code it would give me.

Does this in fact set up a working many-to-many relationship with join table and everything? I'm having some trouble visualising it... Maybe this is for non-Core EF?

```
modelBuilder.Entity<global::EFDesigner.Entity1>()
                     .ToTable("Entity1")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::EFDesigner.Entity1>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

         modelBuilder.Entity<global::EFDesigner.Entity2>()
                     .ToTable("Entity2")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::EFDesigner.Entity2>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<global::EFDesigner.Entity2>()
                     .HasMany(x => x.Entity1)
                     .WithMany(x => x.Entity2)
                     .Map(x => { x.ToTable("Entity1_x_Entity2"); x.MapRightKey("Entity1_Id"); x.MapLeftKey("Entity2_Id"); });
```

If that's all that's needed that would be awesome, your designer would make this so much easier to set up for me then. If not, what has to be done to make it functional?

Thanks in advance

**Comment by msawczyn** [comment]
Unfortunately, many-to-many relationships are only fully implemented (with shadow join tables) in EF6. This isn't a limitation of the designer ... it's a limitation of EFCore. I do see, however, that this is scheduled to be implemented in the next EFCore release, so we can keep our fingers crossed.

I had looked at doing my own naive implementation in the generated code from the designer but, in the end, decided not to do that. When the real version came out, folks would have to deal with any differences, and I didn't want to put anyone through that.

For now many-to-many associations will have to be done as per https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many
