### ISSUE TITLE
HasDefaultSchema doesn't work with MySql

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#160]
When generating DataContext from template, method HasDefaultSchema() is called within method OnModelCreating(). Designer does not allow to set db schema as empty field, but in MySql case I don't have schema and this field causes my code not to work. Workaround to set empty schema in partial method OnModelCreatedImpl() does not work since HasDefaultSchema() can not accept empty string. I found solution to edit template and delete line that renders this method. 
I guess possible solution for this would be to set default schema field in designer as non mandatory and if the field is empty not to generate this line in DbContext generation.

**Comment by msawczyn** [comment]
The designer's been changed to allow the Database Schema property to be empty. Thanks for the report.
