### ISSUE TITLE
Multiple Diagram add entity error

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#163]
Created new model.
Added second view.
Add entity.
Get error.
![EFModel Error](https://user-images.githubusercontent.com/392415/77675176-d2506000-6f49-11ea-881a-6aa0524c23ec.JPG)

**Comment by dcastenholz** [comment]
Actually, I am getting this error on a lot of different operations.

**Comment by msawczyn** [comment]
Which version?

**Comment by dcastenholz** [comment]
It was 2.0.0.0.  I will try the latest when I get a chance.  You can close for now.
