### ISSUE TITLE
MEF Question

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#169]
Is it possible to add new properties to a ModelClass or an Attribute through MEF?  I want to have these show up in the properties dialog.

**Comment by msawczyn** [comment]
Not via MEF, unfortunately. Microsoft's out-of-the-box support for MEF extensions is limited to menu commands, drag-and-drop handlers, and validations. Adding properties via the standard Microsoft Modeling SDK mechanism isn't all that difficult, though, if you limit it to just adding those properties and don't get in the weeds of validations, type descriptors, linked values, etc. -- that's when it starts getting a tad complicated. 

One caveat, though, is that this branches from the main project and you'll have difficulties moving forward. Not saying it's an impossible task, but you'll certainly need to stay on top of it as the project progresses.

**Comment by dcastenholz** [comment]
I have MEF working on my extension now.  That will give me most of what I need.  I will try to do a pull request that makes sense for the main code trunk.  I will make sure that it is very generic and reusable.  I've been wanting to get in and contribute anyway.
