### ISSUE TITLE
Schema Warnings

### ISSUE THREAD

**Issue by TSMarcus** [msawczyn/EFDesigner#170]
I' using Visual Studio 2019 Community Edition and Version 2.0.0.4 of EFDesigner. I create a new empty solution and then add Class Library (.Net Core) as a project. I then add a Entity Framework Visual Editor. At this point, the .efmodel opens and I have two warnings that I can't get rid of. The warnings are...

 Cannot find a schema that defines target namespace 'http://schemas.microsoft.com/dsltools/EFModel', schema validation skipped.

and

 Cannot find a schema that defines target namespace 'http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core', schema validation skipped.

What exactly am I missing?

**Comment by msawczyn** [comment]
Nothing you're missing. That's a warning that you'll see with many projects that are based on the Microsoft Modeling SDK; it just means that Visual Studio is trying to validate the .efmodel file (which is XML based) and can't find the XSD to validate it. The warning can be safely ignored, but I can see how it might cause confusion. I've added an issue to the project and that warning will be eliminated before the 2.0 release.

Thanks for the report!
