### ISSUE TITLE
EFDesigner is not on marketplaces findable

### ISSUE THREAD

**Issue by mwesterm** [msawczyn/EFDesigner#172]
If I try to follow the Link "https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner" I got a not-found-error. Text-Searching at marketplace give also no result.
![2020-04-12_10-14-44](https://user-images.githubusercontent.com/2657830/79064120-84a45900-7ca6-11ea-89b6-5943ca931036.png)

**Comment by msawczyn** [comment]
There was a glitch. Please try again.

**Comment by IoTFier** [comment]
Hi @msawczyn, thank you. I see the nuget in the market place.
But, from the last commit, it shows the CI build was failed.
**Is the version 2.0.6 from this commit point ?**

![image](https://user-images.githubusercontent.com/26844611/79093815-0cc44600-7d1b-11ea-94fc-eaf5375a69ce.png)
