### ISSUE TITLE
Changing String Column Name Clears Max Length Property

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#173]
When you have a string column e. g. with a max length of `255` set and you change the name of this column it clears the max length property.

Is there a technical requirement to do this?

I mean it's nothing super problematic as you can just fill in the max length property again, but it's a bit dangerous as you need to remember the value first and don't forget to add it back in (so a potential risk of unnecessary mistakes).

**Comment by msawczyn** [comment]
No, that shouldn't happen. Thanks, I'll fix that. Are you changing the column name or the property name?

**Comment by ab-tools** [comment]
Thanks for your quick reply, Michael!

I was changing the property "Name".
When I change the "Column Name" property it does not clear the "Max Length" field, just with the property "Name".

**Comment by msawczyn** [comment]
Nice catch. That was part of a feature that never got documented, no one ever used, and wasn't implemented 100%, so now it's gone. As is the problem.
