### ISSUE TITLE
Unable to Create new model for a blank .dll

### ISSUE THREAD

**Issue by cobaltsoftware** [msawczyn/EFDesigner#174]
Hello!
First, I'm excited about your project (I miss the old EF Designer)! Unfortunately though, I have not been able to even bring the tool into my IDE.   

I followed the Getting Started instructions, and I'm having trouble importing the tool using Nuget.

Suggestions welcome!

**Comment by msawczyn** [comment]
What version of Visual Studio are you using? The current version of the designer, v2.0, requires VS2019. Older versions of the designer also support v2017, but won't have any bug fixes or enhancements added.

**Comment by cobaltsoftware** [comment]
I'm running 2019 Pro. I did manage to find the .zip package with the .visx installer in it, and am running that. That said, I've run into an issue (image attached), with all VS realted IDE's shut down (including SSMS).

![EFDesigner Issue](https://user-images.githubusercontent.com/209409/79128172-508d6e80-7d60-11ea-856b-ce6b11212429.JPG)

**Comment by cobaltsoftware** [comment]
I have stopped the installer, and will restart my machine (it's due for one anyway). once back online, I'll let you know if I can get to the tool in a blank project

**Comment by msawczyn** [comment]
The dialog you show is the VSIX installer, and isn't unique to the designer's install. VS won't install anything as long as any of its child processes are running. I see that a lot, and typically do a `End Tasks` to let it do its thing.

**Comment by cobaltsoftware** [comment]
I'm back, and it took a full restart, removing a tool that I had from another vendor, and finding the extension in the Nuget packages to install for the IDE. moving on to checking for a project now. I'll be in touch

Thanks for your patience.

**Comment by cobaltsoftware** [comment]
The entire process actually worked. the option showed up in the Add New dialogue and everything. Now it's just a matter of getting to know this new tool, I think I'm gonna like it ... A LOT!!!

**Comment by cobaltsoftware** [comment]
I was also able to add the tool to an existing project. The only hiccup that I see is not being able to connect to an existing database, and deconstructing from there.

**Comment by msawczyn** [comment]
Sourcing from a database isn't in scope for the designer since there are a number of tools that already do that, and do it well. It's pretty much all I can do to keep up with the changes in EFCore right now, along with new features here and there. That being said, if you use one of those tools and get a compiled assembly with a DbContext, you can consume that in the designer and have a model. So there's a (unfortunately longer) way to get around that.

**Comment by msawczyn** [comment]
Oh, and if it turns out that you do like it ... a lot ... feel free to rate in the VS Marketplace. Never hurts to have more stars!
