### ISSUE TITLE
VS Crash

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#177]
If you open the Entity Model Explorer, and then expand the Diagrams folder, then double-click on the Diagrams folder, it crashes VS.

And, "No", I was not a QA person in a former life.

**Comment by dcastenholz** [comment]
Also does it on the other top level nodes.

**Comment by msawczyn** [comment]
Impressive! Now to see what's going on deep in COM land that causes that, and if it even _can_ be prevented :-(
