### ISSUE TITLE
[Enhancement] Add Collection<object> to the Model classes

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#178]
If it was possible to add a List<object> property named something like ExtendedProperties to ModelRoot, ModelClass, ModelAttribute, and ModelEnum would be SUPER helpful for extending the usage of the designer.  NavigationProperty or BiDirectionalTargets and UnidirectionalTargets would be the other need, but I am not sure which way would be best.

If the objects are serializable, they would be saved in the model file, eliminating the need to save a partner file with all of the extra data I need to store.  I realize that this might not be used a lot, but it could be completely hidden from the casual user, but still allow almost unlimited customization.  That coupled with MEF, and it would be a great platform for extending.  I don't think that it would be complicated to implement, but I may be wrong.

Think of it like CustomAttributes on steroids!

Thanks for considering.

**Comment by dcastenholz** [comment]
Just had a thought.  This could even be ExtendedProperty object.  Don't need a list, as that could be done by the user.

I figure that if I make the request simple enough, then I might get it sooner!!

**Comment by msawczyn** [comment]
I'm a bit confused, though. Why wouldn't this just be something in the
partial class? You could ensure the collection's presence via the T4.

**Comment by dcastenholz** [comment]
I want the object to persist with saving the efmodel.  If that is possible right now, I don't know how.

**Comment by msawczyn** [comment]
After giving this a lot of consideration, I'm afraid that this kind of feature just isn't right for the designer. It's not directly related to creating Entity Framework code (more of a generalized object modeling angle, as I see it), and there's just so much going on now I really don't want to cause confusion by introducing a feature that can't be understood by going to Microsoft's standard documentation.

I think I'm going to have to pass on this, but as always, I do appreciate the request and desire to make the tool better for everyone.
