### ISSUE TITLE
Feature Request - Auto Set Width of Entities the diagram

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner#180]
Hi @msawczyn

This is a feature request - It will be nice to have an option where entities drawn on the diagram will get width size to show the longest content to be displayed for one / more of its attributes.

Thank you.

**Comment by msawczyn** [comment]
I've looked into it and, unfortunately, that looks like it's extremely difficult to do. Not saying that it can't be done, just that the benefit of the feature doesn't outweigh the pain of modifying the Modeling SDK to make that happen. It seems they purposefully tried to discourage that ... who am I to argue?

So I'm going to have to pass on this request. That's not to say some intrepid soul won't pick it up; just not me.

**Comment by IoTFier** [comment]
Thanks @msawczyn.

In which MS Github repo, I could submit this feature request ?

**Comment by msawczyn** [comment]
To my knowledge, they have not open sourced the Modeling SDK (formerly known as DSL Tools). Nor has it changed much since 2008.
