### ISSUE TITLE
EFDesigner 2.0.2 prerelease - Enhancements requests

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner#183]
Hi @michael-sawczyn,

In reference to EFDesigner 2.0.2 prerelease, please here are few requests  -

1> When we add a new .efmodel diagram in the project, in its properties window,  can we have a **default namespaces** ending with suffix denoting plural of the target types ?
e.g. instead of 
![image](https://user-images.githubusercontent.com/26844611/79829998-19bfe580-836a-11ea-97c2-83fa7edde7e8.png)

can we have those default namespaces as below -
![image](https://user-images.githubusercontent.com/26844611/79830286-b84c4680-836a-11ea-8a76-35c1760bb5fe.png)

2> **Output folders path** - 
       2.1> Can there default folders corresponding to the same suffixes as shown in the requested namespace diagram above in # 1?
       2.2> **Can output folders point to folders of a separate class library project** ? It may not be
desirable to package .efmodel and other artifacts in the final application build artifacts (e.g. Mobile
App - iOS bundle or Android - APK )

3> Aligning with .Net (Core) roadmap, should the **default Entity Framework** be EFCore instead of EF6 ?

4> What **option** should be selected **for SQLServer 2019**? "SqlServer " ?

Thank you

**Comment by msawczyn** [comment]
**1)** While the documentation _suggests_ that kind of a namespace structure, the tool shouldn't _impose_ it as the default. It's not a big deal to change it, and different users will have different ideas as to what to do for the optimal namespacing.

**2) [2.1]** -Same as 1). In addition, output folders need to exist prior to being set, so the tool would have to create them on installation, and this would be too much of an imposition.
**[2.2]** That would assume a static relative structure of the projects, which is problematic. To accomplish what you're asking for, one would create the model in a .NET Standard library.

**3)** That's planned to happen when EFCore 5.0 is released.

**4)** While this is a minor optimization option, it's discussed in  https://msawczyn.github.io/EFDesigner/Using-the-designer.html#design-surface-properties . For SqlServer 2019 the value is `SqlServer2012`

**Comment by IoTFier** [comment]
Hi @msawczyn, thank you for the explanation. 

Reg 2.2 - my project is of type .Net Standard Library in which I am designing EFModel and output folder. Did you mean copy generated assets manually in a separate .Net standard library project? If so, I was suggesting if the properties panel of EFModel could take a file system path and not relative structure of the project.

**Comment by msawczyn** [comment]
What's preventing you from creating the output in the project you're working in? If you want to encapsulate it into another library, you can do that too.. But generated code files, no matter the tool that generates them, need to stay within the confines of their project. To do otherwise invites chaos.
