### ISSUE TITLE
EFDesigner 2.0.2 Prerelease - Build fails with errors for generated dbcontext class 

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner#184]
Hi @msawczyn ,

In reference to #182 - see the updated repro solution.
Repro solution - 
[Test.EFDesigner-04.21.20.zip](https://github.com/msawczyn/EFDesigner/files/4508090/Test.EFDesigner-04.21.20.zip)

Project build fails with errors in the generated database dbcontext class - 

1>  'ModelBuilder' does not contain a definition for 'HasDefaultSchema' and no accessible extension method 'HasDefaultSchema' accepting a first argument of type 'ModelBuilder' could be found (are you missing a using directive or an assembly reference?)	Test.EFDesigner.EFVisualEditor	..\Test.EFDesigner\Test.EFDesigner.EFVisualEditor\DBContext\chinook_noaffinity.efd.g.cs	63	Active

2> in initializing table entities with no param value inside .ToTable("")
e.g. for Table Albums - 
         modelBuilder.Entity<global::Test.EFDesigner.Domain.Entities.albums>()
                     **_.ToTable("")_**  <= throws error 

![image](https://user-images.githubusercontent.com/26844611/79832184-7fae6c00-836e-11ea-92d7-281174beb39f.png)

I would appreciate your guidance in resolving these errors.

Thank you

**Comment by msawczyn** [comment]
You're missing a reference to `Microsoft.EntityFrameworkCore.Relational`

**Comment by IoTFier** [comment]
Hi @msawczyn , yes, I was missing reference to Microsoft.EntityFrameworkCore.Relational.
Just wondering why it didn't suggest me to install this package as I build that project ?
It did offer that suggestion for Microsoft.EntityFrameworkCore when I did my first build.

**Comment by msawczyn** [comment]
Don't know. Not sure what 'it' is either: the designer, Visual Studio, MSBuild or NuGet? The designer doesn't do that, MSBuild doesn't know any better, NuGet doesn't bundle the files for EFCore like it does for EF6, and I don't think Visual Studio has anything built into it to detect that. Resharper might, but I haven't tried seeing what it does with that kind of error.
