### ISSUE TITLE
EFDesigner with mysql Pomelo

### ISSUE THREAD

**Issue by khaled0b** [msawczyn/EFDesigner#187]
How to link DbContext with mysql database
In Design Assistant to build a table for me and how to run it to build tables after I designed it

**Comment by msawczyn** [comment]
Once your object model (not table model ... there's a difference) is created and the code for your entity classes and DbContext is generated, you'll go through the standard Entity Framework process of adding migrations and updating the database. 

If you're new to Entity Framework, I'd suggest starting at any of the various Entity Framework tutorials on the internet. Note that there's a difference between Entity Framework 6 and Entity Framework Core, so keep close eye on which tutorial you're reading.
