### ISSUE TITLE
DSL/T4: Allow collections of owned types for EFCore >= v2.2

### ISSUE THREAD

**Issue by pas059** [msawczyn/EFDesigner#190]
Hello,

Is there a way to create a relation one-to_many between a normal entity and  dependant entities with   EFdesigner? such relation that corresponds to a OwnsMany() call.

Regards
Pascal

Related to #198

**Comment by msawczyn** [comment]
There are some updates that need to be made due to enhancements in EFCore after 2.1. That effort is the next set of work items on deck for the designer, and support for OwnsMany is one of those..

**Comment by pas059** [comment]
ok, good news,
best regards

**Comment by msawczyn** [comment]
https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types
