### ISSUE TITLE
Fixed Length String Column Database Type

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#199]
I noticed that a column of type `String` with a fixed length (`Max Length` == `Min Length`) gets a MySQL column type of `VARCHAR` where I would expect `CHAR` instead.

Not sure if that's something EFDesigner takes care of or the underlying data provider, but perhaps you have an idea/opinion about that.

Thanks a lot
Andreas

**Comment by msawczyn** [comment]
It's the provider. The designer doesn't specify database type unless you add an override, which you can do by setting the `Column Type` of the `Property` you'd like to change.

**Comment by ab-tools** [comment]
I see, thanks, Michael, I'll then just set the `Column Type` manually to `CHAR`.
