### ISSUE TITLE
Print / Print Preview hangs when grid is visible

### ISSUE THREAD

**Issue by chhaan** [msawczyn/EFDesigner#201]
When the property 'Show Grid' in the model is set to true, printing and print preview hangs and Visual Studio is closed / aborted.

Tested with:
Visual Studio 2019 16.5.5 
Entity Framework Visual Editor v2.0.2 & v2.0.4.1

Workaround:
Disable grid before printing

Suggested behavior:
Automatically disable and reenable grid when printing.

**Comment by msawczyn** [comment]
Can't reproduce in VS 16.6.2

**Comment by msawczyn** [comment]
Closed due to inactivity. If a reproducible example can be attached, please re-open.
