### ISSUE TITLE
Unable to use the same name for multiple entities in separate schemas: DbSet name ... already in use

### ISSUE THREAD

**Issue by seriusbalrog** [msawczyn/EFDesigner#202]
When I try to define two or more entities with the same name, using different schema and namespace, I get the error message "DbSet name ... already in use". However in SQL it is allowed to use the same table name as long as they belong to different schemas.

**Comment by msawczyn** [comment]
Yes. The `DbSet` name is the name of the C# property in the DbContext, so can't be duplicated. That being said, it doesn't have to match the name of the class or the table, and is something that can be changed in the designer. 

Select that class in the designer and, in the VS Property pane, change the `DbSet Name` value in the `Code Generation` category to whatever makes sense to you for your code.

**Comment by seriusbalrog** [comment]
None of these (`DbSet Name`, `Name`, `Table Name`) are allowed to be duplicated, regardless of their `Namespace` or `Database Schema`. I understand that the `DbSet Name` is an exception, however the rest should be allowed.

**Comment by msawczyn** [comment]
You're right that classes and tables should check identifier uniqueness using their fully qualified names. I've added it as a bug. Thanks for this report! Oddly enough, this is the first time it's been brought up, although this has been the behavior since the designer's been released.
