### ISSUE TITLE
Importing compiled assembly gives "Object reference is not set to an instance of an object"

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#203]
Hi Michael,
The title is self-explanatory I think. I have a compiled assembly (dll) which contains a DbContext-derived class in it (EF6), but when I drag'n'drop it on the model surface I get the title error. Any ideas? 
The caveat is that the assebly/model has been created using the nHydrate designer (https://github.com/nHydrate/nHydrate). 

Does this ring a bell?
Best,
Alex

**Comment by msawczyn** [comment]
Alex,

When consuming a compiled assembly, the designer targets the EF metadata and interrogates it to find the various items it needs to add to the current model. I'm not familiar with what nHydrate is doing, but there may be something either they're not adding or the designer isn't null-checking. I'll certainly take a look.

**Comment by alprinias** [comment]
Michael,
Thanks for your immediate response. If it might help, I could send the compiled assembly to your email. Let me know.
Alex

**Comment by msawczyn** [comment]
That would be terrific. You can send it to michaelsawczyn[at]gmail[dot]com.

**Comment by alprinias** [comment]
Dear Michael,

I have sent you the compiled assembly on weTransfer because gmail wouldn't let me add a dll file,
but I got a notification today that you haven't downloaded it yet and it will expire on June 14. Of course I can resend it, but was wondering whether you saw it or not.

I have resend you the wetrnsfer link just now.

Best, Alex

**Comment by msawczyn** [comment]
Alex,

No, I hadn't seen it, but was able to download it now. I'll dig into it over the weekend. Hopefully it'll be a quick fix.

Thanks!

**Comment by alprinias** [comment]
Hi Michael,
Anything new on this?
Thank you.

**Comment by msawczyn** [comment]
Alex,

I realized that I hadn't posted my discoveries here ... the past few months have been very very busy with paying work.

The assembly in question had dependencies on other assemblies that weren't immediately available - the first one it ran across was an odbc driver assembly. To do assembly digestion, it has to load and instanciate the DbContext. Without the requisite dependencies, it can't do that.

That made it clear that the errors it throws aren't easily discoverable while you're in the IDE, so I enhanced that in 2.0.5.

**Comment by alprinias** [comment]
Michael, thank you for your answer, I completely understand your involvement with paying work, it must always by a priority !

I'm a bit confused with your final sentence ... does it mean that you made it work with the introduced "enhancement" in 2.0.5 ?

**Comment by msawczyn** [comment]
No, it still can't find the dependent assemblies (since they aren't either loaded in memory already or in the same directory as the DbContext assembly). I have, though, enhanced the log messages to output both to the Output window and to display a modal telling you where the log file is. That should make them more easily discoverable. In the log, it's clear exactly why it couldn't parse the DbContext assembly, so will be easy to correct the problem.
