### ISSUE TITLE
Custom Type Support for json fields?

### ISSUE THREAD

**Issue by msounthar** [msawczyn/EFDesigner#206]
Hello

Is it possible to create a POCO mapping for a json column like described below in the EFDesigner?

https://www.npgsql.org/efcore/mapping/json.html

Thanks

**Comment by msawczyn** [comment]
Since it appears to be a postgres-specific feature, it's not appropriate for inclusion in the modeler, although the modeler's customization features support it. You should be able to add that by adding an Attribute to the appropriate Property in the model file.
