### ISSUE TITLE
How to import from EFCore3Parser output json file

### ISSUE THREAD

**Issue by sr3dna** [msawczyn/EFDesigner#207]
I am trying to import classes from a compiled assembly.  Since that DLL contains multiple classes derived from DbContext, I tried to call the EFCore3Parser from command line so that I can provide the optional parameter 'FullyQualifiedClassName'.  

All is well, I got an 'Success' (according to the log) after running EFCore3Parser.exe and got a JSON output file with several hundreds kilobytes of stuff in it.  But then I don't know what to do with that output file.  In the documentation it only mentions how to import from source code or assemblies.  Would you please point me to the right direction?  

Thanks in advance
Andy

**Comment by sr3dna** [comment]
I looked at the source codes and it appears to me I should be able to drag and drop the output json file onto the design surface for it to start processing the file.  I am going to try that and see what happen.  Thanks.

**Comment by msawczyn** [comment]
Hi @sr3dna ,

There's currently no support for importing the temp file created by the assembly parsers. I have, though, put in an enhancement request for the designer asking the user which context to process if it finds more than one available. Yours is the first case I've run across where multiple DbContext-derived classes were included in an assembly ... it just hasn't come up yet :-) 

Thanks for the question.

-- Michael

**Comment by sr3dna** [comment]
Michael,

Thanks for the reply.  In that case, I can work around it.  Not a problem.  Thanks!

Regards,
Andy
