### ISSUE TITLE
Default Diagram error

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#208]
Create new item efmodeler file.  The default diagram name is Diagram.  Click on it in the model properties and it throws an error.  See attached jpg.
![EFModeler Diagram Error](https://user-images.githubusercontent.com/392415/88110881-ce33f800-cb61-11ea-8fbb-055e7fef1bb9.JPG)

Additionally, deleting this diagram crashes the designer.

**Comment by msawczyn** [comment]
Thanks for the report. This shouldn't be possible.

**Comment by msawczyn** [comment]
Is this something you can reproduce and attach a simple example? I can't repro.

**Comment by msawczyn** [comment]
Close due to inactivity
