### ISSUE TITLE
Generate model clasess from code ?

### ISSUE THREAD

**Issue by Diaskhan** [msawczyn/EFDesigner#21]
Its possible to generate code from code ?

Could U guide how it is possible ?
I have own metamodel that I put in DB!
And i want to make enterprise ORm genrator 

![image](https://user-images.githubusercontent.com/15046677/45304712-79bd9b80-b53a-11e8-9f0e-2c7bd57ef888.png)

generating tables and coulmns are ready, further need generation of class models and ientityconfiguration

**Comment by msawczyn** [comment]
That's a pretty big question -- too big to answer here. And this really isn't the forum for that kind of question. Good luck, though!
