### ISSUE TITLE
Cannot open .efmodel "Could not load type 'Microsoft.VisualStudio.ErrorHandler'

### ISSUE THREAD

**Issue by Cyclonit** [msawczyn/EFDesigner#211]
Hi,

I updated EFDesigner to Version 2.0.5.3 today and can no longer open my .efmodel. I get the following error:

`Cannot load '<Path to Project>\<Project>.efmodel': Could not load type 'Microsoft.VisualStudio.ErrorHandler' from assembly 'Microsoft.VisualStudio.Shell.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Any help would be much appreciated.

**Comment by Cyclonit** [comment]
The error occurs on newly created .efmodel files too.

**Comment by msawczyn** [comment]
That's a new one. Which version of Visual Studio are you using, and which version of the designer?

**Comment by Cyclonit** [comment]
I updated VisualStudio to version 16.7.2 and it works again.
