### ISSUE TITLE
Foreign key crashes when reference is on the derived table

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#212]
When you have model that contains one base entity and 2 derived entities (example: WorkItem as a base entity and RemediationTicket and CAPA as derived entities) and then you try to set relation one to many between derived entities, designer generates he following code in dbContext OnModelCreating method:

`modelBuilder.Entity<global::Novolyze.Ticketing.Services.Model.Capa>()
                     .HasOne(x => x.RemediationTicket)
                     .WithMany(x => x.Capas)
                     .HasForeignKey();`

HasForeignKey() crashes at runtime since it must have FK name. As I can see, the issue is probably because FK name is constructed by the designer by concatenating relation name and Id field, but in this case Id field does not exist in derived entity but in the base one. So, in this case method: .HasForeignKey("RemediationTicket_Id") should be generated, but obviously designer does not know to do that. 

I tried various workarounds but didn't find the appropriate one. I can add key name manually, but designer will overwrite it on every change. Can this bug be fixed?

**Comment by msawczyn** [comment]
Absolutely. I'll try to get to that today. Thanks for the report.

**Comment by mciprijanovic** [comment]
Thanks for ultra quick response. When can we expect fix to be in production?
