### ISSUE TITLE
Cannot drag assembly onto the design surface

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#213]
I want to upgrade an old version (1.3.010) to the newest version (2.0.5.5), because i cannot open my efmodel file any more. When dragging the assembly to the design surface mouse cursor immediately tells me that this operation is not allowed. On drop nothing happen. No error or warning found. Is it now no more possible to simply drag a dll file to the design surface? Or which way do you suggest to upgrade to the newest version?

**Comment by msawczyn** [comment]
Yes, that's still a feature. But your being unable to open the efmodel is curious ... nothing should prevent you from doing that. It may be the same thing that's preventing you from using the toolbox, though.

If you would like me to look at the efmodel file and see if I find anything amiss, I'd be happy to do that.

**Comment by ANM86** [comment]
To which mail address should i send the efmodel file?

Am 09.09.2020 18:30 schrieb Michael Sawczyn <notifications@github.com>:

Yes, that's still a feature. But your being unable to open the efmodel is curious ... nothing should prevent you from doing that. It may be the same thing that's preventing you from using the toolbox, though.

If you would like me to look at the efmodel file and see if I find anything amiss, I'd be happy to do that.

**Comment by ANM86** [comment]
One thing I've tried now is to copy all over from an other machine with EF Designer 1.3.0.10 to the new version on my regular development installation. But on pasting the full model i get the error "object reference not set to an instance of an object". Copy paste with one singular entity class would work, but of course I'm losing all my associations. 
Btw. Dragging the .dll File onto the design surface does not work in my old installation either. As soon as I enter VS2019 it changes to a not-allowed mouse cursor

**Comment by ANM86** [comment]
After some investigation I found out that some unidirectionalTargets within my efmodel caused that the file couldnt be opened with v2.0.5.5 I've no removed them (could not recognize why they made troubles) and now a can go on with my existing model and the new designer version.

**Comment by msawczyn** [comment]
Well, it's good news that you're unblocked. I would, though, still be interested in seeing an assembly that couldn't be consumed by the designer. You can send it to efmodeler [at] gmail [dot] com

**Comment by msawczyn** [comment]
Closing since this is resolved
