### ISSUE TITLE
Compile Errors in All Entity Classes after Upgrade from 2.0.1 to 2.0.5.5

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#215]
Just updated EFDesigner in Visual Studio 2019 (16.6.0 Preview 6.0) from version 2.0.1 to 2.0.5.5 and after opening an existent model and saving it again (without any changes) all entity classes were re-generated and are completely broken now.

Basically all local variable names got removed, looking like this now:
![grafik](https://user-images.githubusercontent.com/1347603/92759257-d6edc100-f38f-11ea-8bec-963229b9f481.png)

The "Title" attribute is defined like this in the designer, can't see something special there:
![grafik](https://user-images.githubusercontent.com/1347603/92759357-f1c03580-f38f-11ea-87e6-668598abe4aa.png)

And again, this happened for ALL attributes/columns (not matter which data type) in ALL entities - so not sure what to do here beside reverting back to the old version... any idea about that?

Thanks in advance
Andreas

P. S.: Talking about EF6 with .NET 4.7.2 here.

**Comment by msawczyn** [comment]
Definitely a bug. It appears that the backing field name is missing. As a preliminary diagnosis (without digging into it) it seems that there is an edge condition where, if AutoProperty = false is already set, the backing field name doesn't get generated when updating an older model. The addition of being able to change the backing field name is a new capability.

As a workaround, if you have the default for AutoProperty set to false, try changing it to true and then back to false. That should cause the default names to generate. Alternatively, if you have AutoProperty set to false on only a few properties (and it doesn't sound like that's the case), just flip them to true and back again to cause the backing field names to get set.

I'll have a fix for that in this evening.

**Comment by ab-tools** [comment]
Much appreciating your really quick reply as always, Michael! :-)

No worries, I've switched back to version 2.0.1 for now and I'm happy to test 2.0.5.6 when you have a fix available - just let me know then.

By the way, looks like for all properties `AutoProperty` is set to `false` - was that the default somewhen in the past?
I would not know why this would be required in my case (as least I couldn't remember at the moment ;-)). Where can I define the default of that to `true`? Then I'll give that a try as well when you have the fix available.
