### ISSUE TITLE
Is it possible to change the name of the generated files?

### ISSUE THREAD

**Issue by karenvc1** [msawczyn/EFDesigner#220]
Hello

I was wondering if it's possible to change the entity output filename in the Entities folder by dropping the .generated part.

e.g. entityname.generated.cs  - >  entityname.cs

I have looked through the tt files and found this code in MultipleOutputHelper.ttinclude file:

   private Manager(ITextTemplatingEngineHost host, StringBuilder template)
   {
      this.host = host;
      this.template = template;
      this.fileNameMarker = ".generated";
   }

and removed the line  this.fileNameMarker = ".generated";.  Of course this may have ramifications but I thought I would try it.   However it doesn't make any difference to the output name - whether I make this change on a local copy in the project or in it's original place.

I have restarted vs and also my pc but no difference.

I would appreciate if if you could advise if this is possible?

Many thanks
Karen Comber

**Comment by msawczyn** [comment]
You're able to change that in the property editor for the design surface. In the "Code Generation" category, the property is "File Name Marker". It can be empty.

**Comment by karenvc1** [comment]
As with my other response...works great and thank you!
