### ISSUE TITLE
Association (VS2019, EFCore 3.1)

### ISSUE THREAD

**Issue by biomade** [msawczyn/EFDesigner#224]
I have a entity (MajCom) with and Id property which is and int and is the PK.
I have another entity (PlatformMajCom) that has a property MajComId, it is an int and would be the FK
When I select the BiDirectional association, I then click the MajCom:Id and I can see the pointer change, I then go to PlatformMajCom: MajcomId and the mouse pointer is a red 'not allowed' symbol. 

I have tried the other direction, still no go. 

So how do I create the association??

**Comment by msawczyn** [comment]
Don't click the property, click and drag from the class. You're creating an association between classes. Once you do that, you'll get the option of creating a foreign key property for it.

Hope that helps.

**Comment by biomade** [comment]
Sorry but no, it does not work. I click the association icon in the tool box then went to the PK in Entity1 (the mouse pointer icon changed) and clicked and dragged to the Entity1Id in Entity 2 and when in between the two, you can see the association line but when I get to the FK, I get the "not" symbol and no association is created

**Comment by msawczyn** [comment]
Try clicking the title of the first class node, then dragging to the second class node. The gesture connects the class Entity1 to the class Entity2, not the property Entity1.Id to the property Entity2.Entity1Id. That's the gesture when designing joins in a database, but here we're designing associations in an object model. 

Give that a go and please let me know if that helps.

That does point out that we need to allow the click/drag gesture to transit down to the class if the property got clicked. That shouldn't be too hard to implement. I'll put that on the list.

**Comment by biomade** [comment]
YES! That did it. Thanks so much for the clarification.
