### ISSUE TITLE
Inheritance, Surface property: Inheritance Strategy  VS2019, EFCore 3.1

### ISSUE THREAD

**Issue by osky50** [msawczyn/EFDesigner#226]
Using EFCore 3.1 and VS2019 , Surface properties is not showing documented property: Inheritance Strategy.

In my diagram designer, I'm using Model Inheritance and when I generate code, it uses "TablePerHierarchy" Strategy, which is not desired. I really would like to use "TablePerConcreteType" which is supported in EFCore 3.1. I'm not able to change Surface property Inheritance Strategy as the property is not there.

**Comment by msawczyn** [comment]
TablePerType is supported in EFCore 5.0, and will be available in the next release of the designer. It's not available before 5.0, so you won't see it as an option. TablePerConcreteType isn't implemented in EFCore yet.

Please see [here](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-type-configuration) for more information.

**Comment by osky50** [comment]
I understand you answer based on Microsof EFCore Doc. I'd like to share this scenario with you as there is something that I'm not understanding. 
The example below shows Inheritance using EFCore 3.1, and when we Add Migration it correctly uses TPT approach to generate DB associated tables. Could a similar approach be takenwhen Designer generates code for EFCore 3.1 ?.

I have this Base Entity Class:
    public class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

    public class Fax : BaseEntity
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public DateTime Date { get; set; }
        public string Notes { get; set; }
        public string AdminNotes { get; set; }
    }

    public class KatanaDbContext : DbContext
    {
        public KatanaDbContext(DbContextOptions<KatanaDbContext> options)
            : base(options) { }
        public DbSet<Fax> Faxes { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
        }
    }

When we Add Migration , again using EFCore 3.1 it generates this:

 public partial class Initwithouttool : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Faxes",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(nullable: false),
                    Date = table.Column<DateTime>(nullable: false),
                    Notes = table.Column<string>(nullable: true),
                    AdminNotes = table.Column<string>(nullable: true),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    UpdatedAt = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Faxes", x => x.Id);
                });
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Faxes");
        }
    }

**Comment by msawczyn** [comment]
Now that EFCore 5.0 is out and the designer supports it (and TPT inheritance), I'm going to close this ticket. Please feel free to reopen if there are additional issues.
