### ISSUE TITLE
Output Locations (Suggestion)

### ISSUE THREAD

**Issue by biomade** [msawczyn/EFDesigner#227]
I am using an Onion Architecture so my Context(s) will be in another project, The output location property only lets you select a folder within the project where the diagram resides. It would be nice if you could select a folder in another project

**Comment by msawczyn** [comment]
Thanks for the suggestion. After thinking about this and doing some research, it's a bit too fragile to break the project boundaries and generate code in a different project. Should the target project name or location purposefully or accidentally change, it would be a real head scratcher trying to figure out why nothing works.

There is a workaround, though. If you copy the [context].tt file into the target project, you can point to the .efmodel file using a relative path and that model doesn't have to be in the same project or, as an extreme, even in the same solution directory structure.
