### ISSUE TITLE
Import from assembly cannot find file or assembly

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#236]
Hi Michael,
Still trying to import my scaffolded classes from an old database. When I do it class by class I get somewhere, but the associations need too much attention to come to their desired state (bidirectional, cardinalities, foreign key column names etc.). So I tried to import the compiled assembly, but I haven't managed to do so. I always get a missing file:

Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

I have tried putting the dll file Microsoft.EntityFrameworkCore.dll and Microsoft.EntityFrameworkCore.SqlServer.dll at the same location from which I drag the assembly (Windows Explorer) to the design surface. Same result.

I have added the dlls to the GAC with gacutil.exe. Same result.

Any ideas?

I append the output I'm getting.

Best,
Alex

Warning: **** Trace Opened Local: 2020-11-07 10:47:01.137 UTC: 2020-11-07 08:47:01.140 ****
Warning: 2020-11-07 10:47:01,146 [1] INFO  EFCore3Parser.Program [(null)] - Starting C:\Users\alpri\AppData\Local\Temp\.net\EFCore3Parser\pktmdfk2.f0j\EFCore3Parser.dll
Warning: 2020-11-07 10:47:01,153 [1] INFO  EFCore3Parser.Program [(null)] - Log file at C:\Users\alpri\AppData\Local\Temp\tmpED2.log
Warning: 2020-11-07 10:47:01,154 [1] INFO  EFCore3Parser.Program [(null)] - Loading D:\Dinaris\Software\Solutions\Psyche\Dinaris.Psyche.Scaffold\bin\Release\netcoreapp3.1\Dinaris.Psyche.Scaffold.dll
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] - Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] - Usage: EFCore3Parser InputFileName OutputFileName [FullyQualifiedClassName]
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] - where
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    (required) InputFileName           - path of assembly containing EF6 DbContext to parse
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    (required) OutputFileName          - path to create JSON file of results
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    (optional) FullyQualifiedClassName - fully-qualified name of DbContext class to process, if more than one available.
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -                                         DbContext class must have a constructor that accepts one parameter of type DbContextOptions<>
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] - Result codes:
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    0   Success
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    1   Bad argument count
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    2   Cannot load assembly
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    3   Cannot write output file
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    4   Cannot create DbContext
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    5   Cannot find appropriate constructor
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] -    6   Ambiguous request
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] - 
Warning: 2020-11-07 10:47:01,163 [1] ERROR EFCore3Parser.Program [(null)] - Exiting with return code 4
Error: Error processing assembly. See Output window or C:\Users\alpri\AppData\Local\Temp\tmpED2.log for further information
Import dropped files: no new elements added

**Comment by alprinias** [comment]
Michael, 
I tried to investigate a bit more, and this is what I've found, hope it helps.
To run the parser, you create a directory in my user Temp folder, C:\...\AppData\Local\Temp\.net\EFCore3Parser\pktmdfk2.f0j.
In there I found several dlls. The Microsoft.EntityFrameworkCore dlls had version 3.1.1, whereas my assembly was compiled with 3.1.9. I replaced the Microsoft.EntityFrameworkCore.dll with the 3.1.9 version, and dragged again my assembly on the design surface. Now it complained for a different file missing, I replaced that, then a different one and so on. But after a point I got a new error, not pointing to any missing file but just saying:

Warning: 2020-11-08 10:57:01,029 [1] ERROR EFCore3Parser.Program [(null)] - Exception has been thrown by the target of an invocation.

And now I'm stuck.. So it seems that the versions going into that temp folder are decided somehow, but if I have compiled with a different version this is not transferred to that folder, even if I have it copied in the same folder from which I drag to the designer surface.

All this with the 2.0.5.3 version. I'll try using the latest and see what happens.

Best,
Alex

**Comment by alprinias** [comment]
UPDATE:
With version 2.0.5.7, when I drag the dll on the designer surface, I only get a 

Error: Could not find file 'C:\Users\alpri\AppData\Local\Temp\tmp442E.log'.
Import dropped files: no new elements added

In that folder there is a tmp442E.tmp file created, not a .log one.

Alex

**Comment by msawczyn** [comment]
You've given me some great information that will help track this down. Using .NET Framework, I'd be loading the assemblies into a separate AppDomain in order to isolate the dependencies while parsing. I consciously didn't do that since I knew we'd be needing to parse .NET Core assemblies as well and AppDomains are a thing of the past there.

It's clear I'm going to need to come up with an alternative and can't rely on the ambient assemblies in the parser to be current.

This is slated to get attention right after the EFCore5 modeling changes are out, since its release is imminent.

Thanks for the insight.

**Comment by alprinias** [comment]
Thank you Michael.

As a workaround, I went back and recompiled my scaffolded classes with 3.1. And then dragged the dll on the design surface and it worked!

Now I'm having problems with the relationships... I don't understand how the designer decided where is the source and where is the target... They are mixed. At least compared to what I have in mind.

Actually, what is the meaning of source and target? As I understand it, there are principal and dependent entities, and the simple idea for me to understand is that the dependent one has the foreign key defined as a property.

From what I have seen in the xml, relationships are defined within the "source" entity element, whereas there is nothing about them defined in the "target" entity. Wouldn't it be simpler that relationships are independent elements having as properties the "principal" and "dependent" entity? At the end of the xml and not in each "source" entity?

I might be missing something, of course!

Alex

**Comment by alprinias** [comment]
Additional:

The string properties of my assemply-imported classes had a [StringLength(nn)] attribute, which was not honored by the importing process, leaving all of them with maxLength="0" in the xml (and with yellow exclamation mark triangles in the designer). A suggestion would be to set the maxLength during the import based on such an attribute. If possible, of course.

**Comment by alprinias** [comment]
Additional:

All tables of the old database I'm trying to import in the designer had a "Timestamp" column, which was scaffolded as Byte[]. It shows, indeed, as Timestamp:Byte[] in the designer. When I open the "Add properties via code" popup to edit a property, I can see the Timestamp:Byte[] in the list. However, when I finish editing and close the popup, the Timestamp is deleted from the designer. It looks like the Byte[] is not recognized and discarded.

**Comment by msawczyn** [comment]
Alex, I'm going to ask you to break off the extra reports at the end of this chain into separate issues. Assembly import has been significantly enhanced, so I'm going to close this ticket -- if there are still import issues, feel free to reopen it. But I don't want to mix this up with other, non-import-related issues so that we can keep focus and prioritize.

Thanks.
