### ISSUE TITLE
Plural on Entities and Associations

### ISSUE THREAD

**Issue by superman-ivan** [msawczyn/EFDesigner#237]
Hello,

Not sure if this is a bug or misconfiguration. Because it works fine on my friend's Visual Studio, and we share the same efmodel file on git. We fail to understand what is the difference, so maybe you can help.
When I create entities (e.g. Car and Wheels) DbSet Name and Table Name are not converted to plural.
![image](https://user-images.githubusercontent.com/22794633/98541739-2f5a1580-2290-11eb-904e-ce2c4520fc17.png)

This alone is not big of an issue, but when I create an association between the two, although it correctly determines multiplicity, the Navigation properties are left singular, even at a point where they should be plural.
![image](https://user-images.githubusercontent.com/22794633/98541834-53b5f200-2290-11eb-8c26-8c594a8573ad.png)

The strangest part is it handles the plurality perfectly on my friend's machine. (same VS, same efmodel file)
Any help is appreciated.

Cheers!

**Comment by msawczyn** [comment]
Pluralization depends on whether you have the Microsoft Pluralization Service available (System.Data.Entity.Design.PluralizationServices). I've only seen it available in English versions of Visual Studio, but it may have other flavors as well. Is it possible you're using a different language version?

**Comment by alprinias** [comment]
I have always been doing the pluralisations by hand, didn't know about this service. Actually how can this be turned on? I have the english version of VS, but do I need to do something extra to enable this?

**Comment by msawczyn** [comment]
It's not a service (like running a service process) that can be turned off or on, but rather a library (providing a "service") that you can use. 

The class is [System.Data.Entity.Design.PluralizationServices.PluralizationService](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.design.pluralizationservices.pluralizationservice?view=netframework-4.8), and it lives in `System.Data.Entity.Design`

Hope that helps.

**Comment by alprinias** [comment]
Thanks. So I just have to add a reference to that assembly/nuget package in my project containing the efmodel, or what?

**Comment by msawczyn** [comment]
From a quick glance on the Nuget package manager, it appears that there are a number of options in that area. Search for "pluralize" and see what works best for you. I use the one from `System.Data.Entity.Design` because I'm already linking that assembly, but you may find something that works better for your use case.
