### ISSUE TITLE
Modelling a class that inherits from IdentityUser?

### ISSUE THREAD

**Issue by bplett-wgtcorp** [msawczyn/EFDesigner#238]
I'm evaluating this tool and have run into my first hurdle.  I have a class that needs to inherit from "IdentityUser<Guid>".  "IdentityUser" is in the "Microsoft.AspNetCore.Identity" namespace.  I don't want "IdentityUser" to appear anywhere except as the base class for my class, though obviously its properties would have to make it into the database.  After code-gen, my class still needs to inherit from "Microsoft.AspNetCore.Identity.IdentityUser<Guid>"

1) Is this possible?
2) If so, how?

Thanks!
Brad.

**Comment by msawczyn** [comment]
Sure! You can manually add Microsoft.AspNetCore.Identity.IdentityUser as the base class in a partial.

**Comment by plettb** [comment]
I've tried that and been unable to make it work.

**Comment by msawczyn** [comment]
Full support for this has been a request for some time now. It's tracked in #53

**Comment by msawczyn** [comment]
Closing. Please follow #53 for further updates.

**Comment by plettb** [comment]
> Closing. Please follow #53 for further updates.

Sounds good.  Thanks a lot!
