### ISSUE TITLE
Concurrency token (Timestamp) in constructor parameters

### ISSUE THREAD

**Issue by lizardking** [msawczyn/EFDesigner#24]
The current implementation of the EFDesigner.ttinclude includes the TimeStamp conccurency token into the parameters of the public constructor with required data and also into the paras of the static Create method.

If I'm not mistaken there is no reaand son why a user should set the conccurency token property and EF core is taking care of this. Therefore I think that the conccurency token property should be excluded from the methods mentioned above.

Remark:
I happpy to share my modified EFDesigner.ttinclude and EFCoreDesigner.ttinclude files, but I at least for now I cant make a pull request, since I just use local copies of these files in my project and have not (yet) forked the EFDesigner project.

**Comment by msawczyn** [comment]
Fixed in v1.2.6.7. Thanks a million for the report!
