### ISSUE TITLE
EFCore 5: Compile Error when Using OnDelete Cascade

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#243]
Hello Michael,

unfortunately, with your last update v3.0, probably due to fixing issue #240, it not even builds anymore.

Here another sample project:
[EFDesignerCoreTest.zip](https://github.com/msawczyn/EFDesigner/files/5617563/EFDesignerCoreTest.zip)

When using the `OnDelete` `Cascade` option you now get a compiler error:
`modelBuilder.Entity<global::EFDesignerCoreTest.Entity1>().Navigation(e => e.EntityImplementation).OnDelete(DeleteBehavior.Cascade);`

Best regards
Andreas

**Comment by msawczyn** [comment]
Thanks for pointing that out. The test case you show is a bit of an edge condition, and didn't have good coverage in the test model.

**Comment by ab-tools** [comment]
Thanks for the quick reply, Michael!

In the example above setting `OnDelete` to `Cascade` would even not be needed as I understand from [here](https://docs.microsoft.com/en-use/ef/core/saving/cascade-delete), because the relation is required and thus `Cascade` equals to `Default` anyway.
So I guess setting it explicitly to `Cascade` shouldn't have a lot of effect, does it?

But I just tried with a non-required relationship where the `Cascade` option is more useful, but it also doesn't like it in that case.

Thanks
Andreas

**Comment by msawczyn** [comment]
Since it was manually changed, the T4 picks that up and generates the code for the cascade command, albeit in the wrong place currently. There's no check to see if it's the same as the default in this case.

**Comment by ab-tools** [comment]
Not sure if that would be possible, but I think it would be a great feature if the designer what show somehow (e. g. by adding a ` (default)` behind `Cascade` or `None`) what the default behavior is.

**Comment by msawczyn** [comment]
Possible, yes, but lots of trouble. The default depends on the cardinalities (multiplicities) of the association, and changing the choices in a property editor isn't something done ad hoc. While it would be a nicety, when you consider development and testing effort, it's more trouble than it's worth.

**Comment by ab-tools** [comment]
I see, yeah, although it would be a nice feature (to keep the model as simple as possible by "informing" the user when he sets a property which is default this way anyway), but if that's a big hazzle to implement, it's probably not worth the effort indeed.

By the way, I tried your new build in the `dist` directory, but I guess that's just not finished in regards of this bug yet:
At least it does not generate any `OnDelete`s anymore for me at all which fixes the compiler error, but is probably not the best solution. ;-) Or I just missed them while looking through the generated code now...

**Comment by msawczyn** [comment]
Released in 3.0.1

**Comment by ab-tools** [comment]
Thanks, Michael, tested and works well for me now!
