### ISSUE TITLE
The toolbox items for add entities, relations,... have disappeared

### ISSUE THREAD

**Issue by rdeharo** [msawczyn/EFDesigner#244]
So I can't add new entities, relations, ... to my diagram.
I have tried all the solutions found on the internet related to "resetting toolbar visual studio 2019" but I have not achieved anything.

Any solution.

**Comment by Mabenan** [comment]
Hi,

I know that you have said that you already tried solutions from the internet. But for me it worked with this solution
https://devdept.zendesk.com/hc/en-us/articles/217842718-Resetting-Toolbox-and-Clearing-the-Toolbox-Cache#:~:text=To%20do%20that%2C%20right%2Dclick,hard%20reset%20of%20the%20Toolbox.

I need to wait a long time in the Toolbox was standing Initialization after some minutes the Toolbox worked fine.

**Comment by msawczyn** [comment]
Thanks for chiming in, @Mabenan . I've experienced this before as well, and `Reset Toolbox` has always worked for me.

**Comment by rdeharo** [comment]
Thanks, I finally got the tools to reappear in the toolbox.

**Comment by msawczyn** [comment]
Glad you got past that. Closing.
