### ISSUE TITLE
upgrade to EF Vsual Editor 3

### ISSUE THREAD

**Issue by pas059** [msawczyn/EFDesigner#247]
Hello,

I just upgrade to EF VisualEditor 3.0.1.3 from 2.... and VisualStudio CE 16.8.3, and now when i open my .efmodel file, there is no tool in the toolbox. If i ask to display all in the toolbox, there is a 'EF model diagram' category but all the items are greyed out.

Any idea?

regards

**Comment by ab-tools** [comment]
Sounds like this one here and `Reset Toolbox` could be worth a try:
https://github.com/msawczyn/EFDesigner/issues/244

**Comment by pas059** [comment]
Hello,
thanks for your reply, and sorry i had not saw this thread. Resetting the toolbox works for me.
Regards,
Pascal
