### ISSUE TITLE
Upgrade to v3.0.1.3 now can't create list of Entities - StackOverflow Error

### ISSUE THREAD

**Issue by MattEvansA45** [msawczyn/EFDesigner#249]
Hi 

I have just upgraded my solution to the latest version of the tool but I'm now getting stackoverlow issues when trying to create a list of entities.  I haven't changed any code or underlying data and the error messages are really unclear.

I can see in the genrated code now for each entities there are references to .CreateDataObjectUnsafe(); methods which i can't find any reference /documentation for

![image](https://user-images.githubusercontent.com/41288088/102211659-d2bfcb00-3ecb-11eb-94c9-3529c0552960.png)

And if i simply try and create a list of entities ie

![image](https://user-images.githubusercontent.com/41288088/102211777-0864b400-3ecc-11eb-92e9-eb7703c01781.png)

I get a stackoverflow error with no helpful info.  

![image](https://user-images.githubusercontent.com/41288088/102211887-33e79e80-3ecc-11eb-8d34-4f929efd1ecf.png)

Apologies this maybe really simple for more experienced developers but I'm really struggling to identify what's wrong

Any help really appreciated

**Comment by msawczyn** [comment]
@MattEvansA45 - Nothing you're doing wrong ... it's my bad. If you update your designer to the version at https://github.com/msawczyn/EFDesigner/blob/master/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix the problem should be fixed. That'll be released as 3.0.2 at some point today.

**Comment by MattEvansA45** [comment]
Thank You Michael, that's working again :)

However I've hit another issue. I'm not sure if its related to the tool or newer versions of EF (I'm using EFCore v5.0.1)  

When i load a list of entities the navigation properties are are empty. I'm not sure if it's related to lazy loading or not(again it was working prior to upgrading), or if i need to change a setting somewhere.

you can see in the screen shot my entity has the foreign key value for the connection entity populated but that actually Connection entity is null.  
![image](https://user-images.githubusercontent.com/41288088/102249686-8770e100-3efa-11eb-83fa-a3e6f4193ef4.png)

I try referencing the navigation entity atributes to see if it would retrieve them but it doesn't.
![image](https://user-images.githubusercontent.com/41288088/102249996-e6cef100-3efa-11eb-975c-9286c4909a6d.png)

I just wondered if there was some change I'm missing?

Many thanks

**Comment by MattEvansA45** [comment]
I'm seeing the same on other entities as well although on this one below,  one of the navigation properties populates correctly (KVConnection) but 2 others don't (DefaultIntegrationStage & SystemType) but i can't see any differencet between the 3 of them in terms of property settings.

Obviously the one that's working has {Castle.Proxies.ConnectionProxy} as the value next to the property but the others have their entity types, but I've no idea how these are set.

![image](https://user-images.githubusercontent.com/41288088/102273107-bc406080-3f19-11eb-9fa8-e9068e218b18.png)

I'm really stumped as to what's changed??

**Comment by msawczyn** [comment]
Hmm. If the only change you made was from EFCore 5.0.0 to EFCore 5.0.1, I'm thinking that the issue doesn't lie in the designer-generated code. 

From what I'm seeing in the screen shot, `DefaultIntegrationStage` and `SystemType` are indeed populated; their foreign key properties are set and it seems that, were you to expand the dropdowns, you'd see properties with values assigned. If they're not collections and weren't assigned, you'd see `null` as the property values.

**Comment by MattEvansA45** [comment]
Hi Michael

Apologies my bad I'd also updated the EF Core from version 3.15 to EF Core 5.

However I've rolled back EF Core and the other associated Nugets back to version 3.1.5 which was working with the original version of the code, however using the latest version of the EFDesigner (3.0.1.4) but setting it to target EFCore & 3.1.Latest  I'm seeing differences in the code generated for the entities and the DBContext  and I'm finding none of the navigation properties are populating correctly even though the foreign key fields are populated. I was originally using version 2.0.4.1 of the tool.

I've included some comparisons of the generated dbcontext file and also a generated entity (Connection) where 3 of its Navigation Properties don't populate (Connection,SystemType &DefaultIntergationStage) 

![image](https://user-images.githubusercontent.com/41288088/102399598-ba89a200-3fd8-11eb-9f17-c151858a3593.png)
![image](https://user-images.githubusercontent.com/41288088/102399910-1d7b3900-3fd9-11eb-9604-0f37e7e70940.png)
![image](https://user-images.githubusercontent.com/41288088/102400081-53b8b880-3fd9-11eb-9b69-a6ae0423db57.png)

and showing that whilst the navigation property field has a value in it, the property itself is null
![image](https://user-images.githubusercontent.com/41288088/102402459-afd10c00-3fdc-11eb-81ca-7d28859ef83a.png)

**Comment by msawczyn** [comment]
@MattEvansA45 - would you be willing to send me the efmodel file so I can give it a go? I haven't a clue what could be going on here. I wouldn't need any of the surrounding code or even the diagramx files; only the .efmodel. If that's ok, you can mail it to michaelsawczyn[at]gmail[dot]com
