### ISSUE TITLE
Don't create DbSets for many to many linking tables?

### ISSUE THREAD

**Issue by Falthazar** [msawczyn/EFDesigner#25]
It looks like in generally, you don't create DbSets for linking tables in many to many relationships in EF core.

On both the EF core docs: https://docs.microsoft.com/en-us/ef/core/modeling/relationships#other-relationship-patterns
and in "EF Core in Action" by Jon Smith (which I'm currently reading) neither create a DbSet for that table.

Two questions - do you know why that is (neither explain it that I've seen)? And, if there a way to configure EFDesigner to do that?

**Comment by Falthazar** [comment]
Thank you so much for the explanation! This is a huge help.

One more sorta related question if you don't mind? 
I have a table of doctors, and need to list all of their specialties (oncology, dermatology, etc.). The list of specialties will grow, and I will need to group docs by specialties later on.

Is there a better way to model look-up tables like this in EF core? Or will I need to have to model these like any other many-to-many relationship with a million little association tables since there will be a couple like this?

Er, do you happen to know of any examples of good database models with EF core?

Again, thank you so much for your help, I really really appreciate it!

Lastly:
> That storage could be ...  a bunch of monks with quill pens on the other end of a cell phone
Any idea on when EF core will support this? I was going to use a SQL server but then I realized how long parchment can last and I think this might be the better option.

**Comment by msawczyn** [comment]
For general lookup objects, I like to use what is essentially a key/value pair object:

```
class Lookup {
   public string Category { get; set; }
   public string Key { get; set; }
   public string Value { get; set; }
}
```

but you're looking for something more specific. I'd just go with a many-to-many association to a really thin Specialty class, which leaves you room to hang additional data in the specialty should it ever come to that.

It's certainly possible to make good models with EF Core, but the lack of many-to-many support means that you just have to work harder. Too much harder, IMHO, but I'm lazy. It'll get there, though. When it hits parity with EF6 (and in some areas it's already passed EF6), we'll look back fondly on these days.
........
Nah.

Lastly: LOL. That's a hardware problem.
