### ISSUE TITLE
Foreign Key Column Names

### ISSUE THREAD

**Issue by superman-ivan** [msawczyn/EFDesigner#250]
Hello Michael,

Great tool! We've been using it a lot for quite a whlie now! My quesition is about foreign key db column names. In v3 it seems the EFVE generates them with no underscore, e.g. .HasForeignKey("CategoryId"), while in v2.x it was with underscore, e.g. .HasForeignKey("Category_Id"), which is a breaking change for us when migrting to v.3.
But since I don't see other people having the same issue, it must be some configuration option we're missing?

Thanks!
Ivan

**Comment by superman-ivan** [comment]
After some digging I found what template modification I need to make to make the tool generate the ".HasForeignKey" calls consistent to the way it was before the template upgrade that came with v3.
Note the underscores in code snipped from EFModelGenerator.ttinclude:

         [SuppressMessage("ReSharper", "ConvertIfStatementToReturnStatement")]
         protected static string CreateShadowPropertyName(Association association, List<string> foreignKeyColumns, ModelAttribute identityAttribute)
         {
            string GetShadowPropertyName(string nameBase)
            {
               if (association.SourceRole == EndpointRole.Dependent)
                  return $"{nameBase}_{identityAttribute.Name}";

               if (association is BidirectionalAssociation)
                  return $"{nameBase}_{identityAttribute.Name}";

               return $"{nameBase}_{identityAttribute.Name}";
            }
Would you consider revisiting the new template implementation to be consistent with the one that came with versions prior to v3? We would highly appreciate that. Thanks!
Ivan

**Comment by msawczyn** [comment]
Hi Ivan,

Yes, that was an unintended change. It needs to be reverted. I think we'll go a step farther and make it a global setting, since different folks like different patterns. I'll add those both patterns. Thanks for pointing it out!
