### ISSUE TITLE
Reverse Association Option

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#253]
Sometimes you would simply like to reverse an association:
It would be great if there would be an easy way to do that without deleting and re-creating it.

I see that there are some right-click commands for associations in the designer already, perhaps it would be possible to add a "Reverse Association" option there as well?

**Comment by msawczyn** [comment]
This only makes sense for unidirectional associations, and there the property name would have to be a default name. I think this is an important enough thing that the user should give it some thought and switch it manually. Thanks for the suggestion, though!
