### ISSUE TITLE
Setting Default Database Collation Results in Compilation Errors

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#258]
Hello Michael,

while doing tests for the #254 issue I've upgraded to your latest version (tested both, v3.0.2.0 and v3.0.2.1 from your commit) and when I see a default database collation I get a lot of compilation errors now.

At the top of the `OnModelCreating` method it first correctly set
`modelBuilder.UseCollation("utf8mb4_0900_ai_ci");`,
but then it adds this line (without quotes!) for every string property:
`.UseCollation(utf8mb4_0900_ai_ci);`

Beside that obviously quotes are missing is it really required to set the default collation for every single string property?
I would expect (at least for MySQL) that the default database collation is automatically used for every table and column if no other collation is specified.

In any case, at least some quotes would be appreciated, thanks. ;-)
Continuing to test #254 now...

Best regards
Andreas

**Comment by msawczyn** [comment]
Not yet ready for prime time....
