### ISSUE TITLE
Method for quickly entering new properties

### ISSUE THREAD

**Issue by mikethibault** [msawczyn/EFDesigner#259]
It would be great if there was a way to not only enter the property name, but also the type and nullability of each property within the designer pane.  Currently (unless I'm missing something), entering many properties requires constant switching between keyboard and mouse.  

SQL Server Management Studio's Table Designer is really efficient at this; Tab brings you between the different fields, up and down arrow scrolls you through the possible types, space toggles nullability.

**Comment by msawczyn** [comment]
Got you covered. Check out [Adding properties via code](https://msawczyn.github.io/EFDesigner/Properties.html#adding-properties-via-code-custom-property-syntax)
