### ISSUE TITLE
Where is general discussion?

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#262]
Michael,

I would like to discuss a feature that I am working on adding.  Where is the appropriate place to do that?

Daniel

**Comment by msawczyn** [comment]
That's an excellent question. The only facility we currently have for that is right here, but that seems less than convenient. 

Any suggestions?

**Comment by dcastenholz** [comment]
Michael,

I have added a context menu to my own VSIX package to allow code generation by right-clicking on a .efmodel file and selecting "Generate Code".

My first question is whether you would consider me moving it to a pull request for inclusion in the designer.  The solution explorer context menu potentially has to be loaded prior to the loading of the designer menu system, but I can handle that in the code.  In the process of writing the menu code, I noticed that EFModelPackage uses ModelingPackage as its base class, rather than AsyncModelingPackage.  This complicates the code, and MS is actively trying to get developers to go async on all packages.  Would you consider switching to AsyncModelingPackage?  If you like the idea of the solution explorer context menu, I will do a PR, but if you would consider switching to AsyncModelingPackage, I will wait, as it will be a less invasive code change.


Thank you,


Daniel


Daniel Castenholz – Senior Software Engineer
San Luis Obispo County Sheriff's Office
Phone: 805.781.4504

[cid:7182796b-5ab1-45fb-9fb9-a4b5bcf7f84a]

________________________________

**Comment by dcastenholz** [comment]
While we are at it, I also have a context menu that works on the designer surface to add an entity or generate code.  Are you interested in a PR for that?

**Comment by dcastenholz** [comment]
OK.  Started a discussion here:https://github.com/msawczyn/EFDesigner/discussions/265#discussioncomment-329007
