### ISSUE TITLE
Support for Required empty String

### ISSUE THREAD

**Issue by MirekK0** [msawczyn/EFDesigner#270]
Is there any chance use property required and AllowEmptyStrings  ? 
Custom Attributes work's, but i need attribute Required set to True and with True can't set Custom Attribute to [Required(AllowEmptyStrings = true)].

Thx
  Mirek

**Comment by msawczyn** [comment]
Changing that validation in the designer would be a big behavior change that would have negative impact on a lot of folks. But, as the code generation is completely customizable, there are ways you can change this for your particular use case. 

Copy the `EFModelGenerator.ttinclude` template into your project. Search for `[Required]` in that file and you'll be able to change that generated code to `[Required(AllowEmptyStrings = true)]` whatever other output you prefer. 

Hope that helps.
