### ISSUE TITLE
Reverse engineering from dll (.net5) fails with FileNotFoundException

### ISSUE THREAD

**Issue by TedKerley** [msawczyn/EFDesigner#273]
Have upgraded to the latest version of the extension and attempted to import a dll using drag and drop from an existing .net 5 project. (Also tried .net core 3 which gives the same error message but from EFCore3Parser)

- Have tried drag and drop from both windows explorer and visual studio.

- The missing dll exists in the folder alongside the dll housing the dbcontext class.
`
Warning: **** Trace Opened Local: 2021-03-01 11:38:38.103 UTC: 2021-03-01 11:38:38.110 ****
Warning: 2021-03-01 11:38:38,123 [1] INFO  EFCore2Parser.Program [(null)] - Starting C:\Users\xxxx\AppData\Local\Temp\.net\EFCore2Parser\5f4bkgjs.mu1\EFCore2Parser.dll
Warning: 2021-03-01 11:38:38,162 [1] INFO  EFCore2Parser.Program [(null)] - Log file at C:\Users\xxxx\AppData\Local\Temp\tmp3744.log
Warning: 2021-03-01 11:38:38,166 [1] INFO  EFCore2Parser.Program [(null)] - Loading C:\Users\xxxx\Source\Repos\Personal\xxxxx\xxxxx\bin\Debug\net5.0\xxxxx.dll
Warning: 2021-03-01 11:38:38,501 [1] ERROR EFCore2Parser.Program [(null)] - Could not load file or assembly 'Microsoft.Extensions.Identity.Stores, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Warning: 2021-03-01 11:38:38,506 [1] ERROR EFCore2Parser.Program [(null)] - Usage: EFCore2Parser InputFileName OutputFileName [FullyQualifiedClassName]
Warning: 2021-03-01 11:38:38,510 [1] ERROR EFCore2Parser.Program [(null)] - where
Warning: 2021-03-01 11:38:38,513 [1] ERROR EFCore2Parser.Program [(null)] -    (required) InputFileName           - path of assembly containing EF6 DbContext to parse
Warning: 2021-03-01 11:38:38,516 [1] ERROR EFCore2Parser.Program [(null)] -    (required) OutputFileName          - path to create JSON file of results
Warning: 2021-03-01 11:38:38,519 [1] ERROR EFCore2Parser.Program [(null)] -    (optional) FullyQualifiedClassName - fully-qualified name of DbContext class to process, if more than one available.
Warning: 2021-03-01 11:38:38,523 [1] ERROR EFCore2Parser.Program [(null)] -                                         DbContext class must have a constructor that accepts one parameter of type DbContextOptions<>
Warning: 2021-03-01 11:38:38,526 [1] ERROR EFCore2Parser.Program [(null)] - Result codes:
Warning: 2021-03-01 11:38:38,530 [1] ERROR EFCore2Parser.Program [(null)] -    0   Success
Warning: 2021-03-01 11:38:38,533 [1] ERROR EFCore2Parser.Program [(null)] -    1   Bad argument count
Warning: 2021-03-01 11:38:38,536 [1] ERROR EFCore2Parser.Program [(null)] -    2   Cannot load assembly
Warning: 2021-03-01 11:38:38,540 [1] ERROR EFCore2Parser.Program [(null)] -    3   Cannot write output file
Warning: 2021-03-01 11:38:38,543 [1] ERROR EFCore2Parser.Program [(null)] -    4   Cannot create DbContext
Warning: 2021-03-01 11:38:38,546 [1] ERROR EFCore2Parser.Program [(null)] -    5   Cannot find appropriate constructor
Warning: 2021-03-01 11:38:38,549 [1] ERROR EFCore2Parser.Program [(null)] -    6   Ambiguous request
Warning: 2021-03-01 11:38:38,552 [1] ERROR EFCore2Parser.Program [(null)] - 
Warning: 2021-03-01 11:38:38,556 [1] ERROR EFCore2Parser.Program [(null)] - Caught FileNotFoundException - Could not load file or assembly 'Microsoft.Extensions.Identity.Stores, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Warning: 2021-03-01 11:38:38,559 [1] ERROR EFCore2Parser.Program [(null)] - Exiting with return code 4
`
I'm wondering if this is a binding redirection issue, but haven't investigated.  I will try dragging and dropping the source code instead.

This is the first time I have attempted to used this feature, so I may be doing something wrong.

The extension is a very professional piece of software, many thanks for all of your hard work!

**Comment by msawczyn** [comment]
@TedKerley - were you able to resolve the issue?

**Comment by TedKerley** [comment]
No - I gave up in the end and used a different technique to connect to the database.
