### ISSUE TITLE
Setting a manual identity type on an identity property throws when trying to save id provided

### ISSUE THREAD

**Issue by OwenPattison** [msawczyn/EFDesigner#274]
Hello,

I've been using the designer tool (v3.0.4.7) to create a new database and part of this requires me to transfer some data from an existing database - here is where my problem lies, when I try to assign a key to my new tables PK I get the following error:

![image](https://user-images.githubusercontent.com/5864244/109800262-db938380-7c14-11eb-948a-35c79247a792.png)

In attempting to do this I'm setting the identity type to `manual` which adds the id to the arguments of the constructor, however, this did not resolve the issue. 

I've also tried to manually set directly to SQL using `SET IDENTITY_INSERT FamilyGroups ON`, I also tried doing this in code by wrapping my `this.context.SaveChangesAsync()` with `this.context.ExecuteSqlRawAsync(@"SET IDENTITY_INSERT dbo.FamilyGroups ON")`.
unfortunately, this has had no effect and I'm still unable to save.

I'm wondering is there something I'm just missing perhaps in using the designer - I couldn't find any related issues here in GitHub or in the documentation?

Any suggestions on this would be greatly appreciated.

Owen

**Comment by msawczyn** [comment]
This works well in a number of projects I've used it in. What exception are you seeing?

**Comment by OwenPattison** [comment]
@msawczyn, I've found the problem with this issue, and it's not linked to the designer so I'm going to close this issue now.

The problem was due to the savechanges not being in a transaction therefore the SQL to turn IDENTITY_INSERT on was not persisted, kind of strange that I had directly changed it with a manual SQL script but this solves my issue anyway, thanks.
