### ISSUE TITLE
Identity Field when Setting Entity to be "Is Database View"

### ISSUE THREAD

**Issue by dongjason** [msawczyn/EFDesigner#275]
Hi, 

I got into an "interlocking" situation. I have an entity, it need to pull the data from a database view.  I added the entity and set the entity's "Database\Is Database View" setting to True.  The designer warned me "[Entity] can't be mapped to a Sql query since it has identity attribute(s) Id. Set their 'Is Identity' property to false first.".  After I set the Id field's "Is Identity" to false, I get a validation error saying "[Entity] Class has no identity property in inheritance chain".

Seems either I have or not have an identity field, there is validation error for it?
![View](https://user-images.githubusercontent.com/8507131/110180457-cca8fe80-7dd7-11eb-9137-050736494f10.PNG)

Jason

**Comment by msawczyn** [comment]
3.0.5 released
