### ISSUE TITLE
Mysql Support

### ISSUE THREAD

**Issue by Netclick19** [msawczyn/EFDesigner#276]
Hi,
I'm trying to use the connection string menu with Mysql, but there isn't any MySql provider to the list.
Is it supported?

Mysql connection works well with my VS2019.

Thank you for your support.

**Comment by msawczyn** [comment]
The list of providers is pulled from what Visual Studio reports, so it's interesting that it doesn't show it in the designer. It'll take some investigating.

**Comment by Netclick19** [comment]
This is the list proposed by Visual Studio 2019
![image](https://user-images.githubusercontent.com/9130333/110454920-1b041900-80c8-11eb-9ff3-3fb3fa7b8fe4.png)

This is the list proposed by EFDesigner
![image](https://user-images.githubusercontent.com/9130333/110454827-03c52b80-80c8-11eb-85ea-c7c71658dc12.png)

**Comment by Netclick19** [comment]
Hi,
do you have any news?
Thank you for your support.

**Comment by msawczyn** [comment]
I would suggest just typing the connection string (or connection string name, based on your usage preference) into the designer property. We're currently only pulling the default datasource providers.

**Comment by MagicAndre1981** [comment]
I have the same for firebird. I see the firebird DDEX provider when I add a new DataConnection in ServerExplorer, 

![efmodel_designer_](https://user-images.githubusercontent.com/8274816/117619807-ff70c980-b16f-11eb-972f-7bb2d888f149.png)

but in your tool I only see Access, ODBC, SQL Server, SQL Server File and Oracle.

![efmodel_designer](https://user-images.githubusercontent.com/8274816/117619824-0566aa80-b170-11eb-86fc-3397e6bca7cc.png)

**Comment by Opzet** [comment]
DDEX is different to Entity Framework Database connector for firebird (Firebird ado.net provider aka Data provider )

   DDEX is just an addin to make a db GUI in Visual Studio  

   Ado.net Data provider compiles ef into native CRUD for your particular db

see https://www.ibprovider.com/eng/documentation/connection_to_firebird_in_visual_studio_2017_via_ddex_provider.html

**Comment by msawczyn** [comment]
Closing as low priority item
