### ISSUE TITLE
No visual designer with latest VS2019 update?

### ISSUE THREAD

**Issue by LRathje** [msawczyn/EFDesigner#277]
Hi
Maybe I'm doing something wrong, but after latest update of VS2019 Community to Version 16.9.0 I can't get the visual designer to work.
- There is no diagram - only fileview when clicking the efmodel file.
- I can't make changes or update code because of this
- When going to Tools->Options->Entity Framework Visual Editor I get the error message that EFModelPackage did not load correctly

I have tried to reinstall the extension V 3.0.4.7 but the problem persists.
I'm seeing this in both .net core 3.1 and 5.0 by the way..

Am I doing something wrong or is there a compatibility problem with the latest VS update?

Best regards
Lars

**Comment by LRathje** [comment]
Still no answer to this critical bug?

Here is from my logfile - it seems to be some composition error (not that I understand much of it):
<entry>
    <record>1192</record>
    <time>2021/03/09 09:15:00.338</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [EFModelPackage]Source: &apos;System.ComponentModel.Composition&apos; Description: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.&#x000D;&#x000A;&#x000D;&#x000A;1) No exports were found that match the constraint: &#x000A;&#x0009;ContractName&#x0009;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&#x000A;&#x0009;RequiredTypeIdentity&#x0009;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&#x000D;&#x000A;&#x000D;&#x000A;Resulting in: Cannot set import &apos;Microsoft.VisualStudio.Modeling.Shell.ExtensionEnablement.CommandExtensionRegistrar.mefImportedLogger (ContractName=&quot;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&quot;)&apos; on part &apos;Sawczyn.EFDesigner.EFModel.ExtensionEnablement.EFModelCommandExtensionRegistrar&apos;.&#x000D;&#x000A;Element: Microsoft.VisualStudio.Modeling.Shell.ExtensionEnablement.CommandExtensionRegistrar.mefImportedLogger (ContractName=&quot;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&quot;) --&gt;  Sawczyn.EFDesigner.EFModel.ExtensionEnablement.EFModelCommandExtensionRegistrar&#x000D;&#x000A;&#x000D;&#x000A;</description>
    <guid>{56BBE1BA-AAEE-4883-848F-E3C8656F8DB2}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by msawczyn** [comment]
Looking into it. I've been quite ill for the past few weeks. This will take some time to investigate, but appears to be related to interactions between the extension and how you have your Visual Studio configured rather than solely an extension issue.

**Comment by LRathje** [comment]
Okay - and thanks for the reply. I hope you're getting well again and wish you a quick recovery..

Let me know if you need further details of my VS setup. I have tried to disable some of my other extenstions to see if it mattered, but no.

Best regards
Lars

**Comment by LRathje** [comment]
Hi
I upgraded VS 2019 Community to new version 16.9.1, which was released today.
I had hoped it would help, but the issue remains..
Just for your information.
Best regards Lars

**Comment by IoTFier** [comment]
> Looking into it. I've been quite ill for the past few weeks. This will take some time to investigate, but appears to be related to interactions between the extension and how you have your Visual Studio configured rather than solely an extension issue.

Hi @msawczyn, how are you feeling now? Best wishes for your speedy recovery. Take care and be safe.

**Comment by LRathje** [comment]
If that's the case, then it sounds much easier to solve. I cross fingers you somehow can nail it - let me know if you need specifics about my configuration.
Lars

**Comment by LRathje** [comment]
Hi
Do you have any idea about if this is going to be solved?
I feel close to let it go and see if I can use Devart, LLBLGen or another to continue with programming. But I would rather stay with EFDesigner if you can make it work again.
Best regards
Lars

**Comment by msawczyn** [comment]
Hi Lars,

I'm sure that by now you've taken a different approach to your EF modeling, or possibly the problem has resolved itself during a Visual Studio upgrade. But if neither of these are the case, I'd suggest starting by reviewing the Visual Studio log file (`devenv -log`) to see if there are interaction errors that jump out there.

These are, frankly, the hardest things to pinpoint and solve since they're unique to each individual.

**Comment by LRathje** [comment]
Hi Michael

Thanks for getting back to my. But yes – I have switched to Devart Entity Developer and got my things to work that way around.

But I hope you get it solved if others also experience that problem.

Best regards
Lars

Fra: Michael Sawczyn ***@***.***>
Sendt: 30. april 2021 09:43
Til: msawczyn/EFDesigner ***@***.***>
Cc: Lars Rathje ***@***.***>; Author ***@***.***>
Emne: Re: [msawczyn/EFDesigner] No visual designer with latest VS2019 update? (#277)


Hi Lars,

I'm sure that by now you've taken a different approach to your EF modeling, or possibly the problem has resolved itself during a Visual Studio upgrade. But if neither of these are the case, I'd suggest starting by reviewing the Visual Studio log file (devenv -log) to see if there are interaction errors that jump out there.

These are, frankly, the hardest things to pinpoint and solve since they're unique to each individual.
