### ISSUE TITLE
Drag-drop issue after update of Designer and VS2017 - Error text good but wrong

### ISSUE THREAD

**Issue by Falthazar** [msawczyn/EFDesigner#28]
Had an issue where I couldn't drag and drop an entity into the designer. Cropped up after updating EF Designer and then VS2017 (to 15.8.6, didn't fix when I updated to 15.8.7).

The error:
> Drag drop operation failed with the following error:
> 
> Domain object with identity 05ea9a33-a0a8-4940-8a76-d870bb991325 was not found in directory.
> 
> A common cause of this exception is an out of date Visual Studio toolbox cache with respect to changes in your domain model. Run "devenv /setup" from the command line to reset this cache.

I tried doing that last bit: Running "devenv/setup" but it doesn't seem to work.
What ended up working was right-clicking the toolbox and selecting "Reset Toolbox", assuming the error is from EF designer maybe the text should be changed to suggest that?

**Comment by msawczyn** [comment]
Yes, I've seen that. And I was able to get back running by doing exactly what you did, the "Reset Toolbox" bit.

The message, unfortunately, doesn't come from the extension, but rather from either Visual Studio or the DSL Tools library, so there's not much I can do to replace it. I can, however, put a note in the docs (possibly an FAQ section?) and mention it.

Thanks for bringing it up!

**Comment by Falthazar** [comment]
Any way to figure out where it is coming from? So I can submit an issue with them, though I guess we're probably SOL if it's VS, pretty sure this would be low on their priority list.

**Comment by msawczyn** [comment]
Unfortunately, I don't, and haven't been able to find the exact source of the message either. I think the best bet is to document it and warn future generations. Thanks again for bringing it up.

**Comment by ensemblebd** [comment]
Anyone encountering this in 2019 who still has a blank toolbox, even after trying:
1. developer prompt -> devenv /setup
2. Right-click Toolbox -> Reset Toolbox
3. Uninstalling extension, closing vstudio, opening vstudio, installing extension, restarting vstudio

Point 3 is usually what worked for me in the past (only happened one other time).
But in this case, nothing worked.

The following is what worked for me:
--> `C:\Users\<USER>\AppData\Local\Microsoft\VisualStudio\<VERSION (15 || 16)>` 
--> Search `*.tbd` , delete. Start vstudio
As Per: https://devdept.zendesk.com/hc/en-us/articles/217842718-Resetting-Toolbox-and-Clearing-the-Toolbox-Cache

**Comment by msawczyn** [comment]
This is something that, while infrequent, appears often enough that it needs to be made easier to find. We need an FAQ page in the docs. I've added it to the List Of Things To Do.

Thanks for posting this tip!
