### ISSUE TITLE
Add Foreign Key Properties Does not Do Anything

### ISSUE THREAD

**Issue by dongjason** [msawczyn/EFDesigner#280]
When I right click in the designer surface and select Add Foreign Key Properties, it does not seem to do anything.  I also tried to select an association or entity and do Add Foreign Key Properties, same, nothing seems to happen.

**Comment by msawczyn** [comment]
I' not sure what your seeing. There is a feature in the backlog similar to that but it's not yet implemented. `Remove Foreign Key Properties` currently exists as a context menu choice on the designer surface; is that what you were referring to?
