### ISSUE TITLE
Error - Value Cannot Be Null. Parameter name: diagramName

### ISSUE THREAD

**Issue by bbehling** [msawczyn/EFDesigner#284]
Getting this error when trying to create a new diagram.

VS 2019
.net Core 3.1

![image](https://user-images.githubusercontent.com/2151622/118297936-082d0c80-b49c-11eb-99ed-62533766758f.png)

**Comment by bbehling** [comment]
I gave the diagram a name, that got rid of the error. But, no entities are loaded in the model. This was added to an existing EF project.

Is this by design where the tool won't show existing entities or an issue?

**Comment by msawczyn** [comment]
Hi @bbehling -

Odd that the diagram wouldn't start out without the default name of `Diagram1`. Also troubling is that, from the image you posted, you were able to delete the main diagram. That shouldn't have been the case. There's validation to ensure that there's always a diagram named the same as the model file. Something else I'll need to look into.

Yes, new diagrams start out blank. Note that diagram's aren't the model ... they're the view. The model explorer tree shows the current state of the model at all times, whereas each diagram can be designed to display the aspect of that model you're interested in showing.
