### ISSUE TITLE
Severe bug in 3.0.5.2

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#286]
Hi Michael, with the version 3.0.5.2 you introduced a bug that disallows us to compile the code. In the constructor of the generated parent object the child property initialization line is not complete so code will not compile. We had to revert back to old version. Strange how this passed the tests...
Another issue/feature/question is: seems like you introduced the feature that in the constructor of the child model child adds itself to the parent collection. This means that we don't need to write line: parent.Childern.Add(child). If we do this, we will get duplicated children in the collection. This was not like described earlier and seems like this change is introduced in 3.0.3 version but not documented. 
Is this intentional since we should now change all the code in order not to have duplicates (although in db it will be OK since EF itself manages this properly and does not write duplicates in db since it detects that it is the same object written twice in collection)?
And also the question is: can I disable this behaviour? Can i configure it somewhere so that I get generated model that does not perform like this to add itself to the parent in constructor.

Thanks.

**Comment by msawczyn** [comment]
These issues should be resolved in the latest pre-release. You're right that it is strange that they passed tests -- I'll have to see exactly how that happened.

If you could try https://github.com/msawczyn/EFDesigner/releases/tag/v3.0.6.1-nightly I would be very thankful. If there are still issues, please let me know.

**Comment by mciprijanovic** [comment]
> `in the constructor of the child model child adds itself to the parent collection`
> This should only be the case when a child object has a required association to the parent. That's been there for quite some time, as I recall. That code comes from `EFModelGenerator.ttinclude` in the `WriteConstructor` method (around line 733, in the latest pre-release).

Well, maybe I am wrong about the version this is introduced, but certanly it was not present before, since a huge piece of our generated code does not have this line in a constructor. According to that we were always writing the line parent.Childern.Add(child), and this now causes the problems when we now edit models with new version. So, the question is, is this feature going to stay like this from now on, or it will be configurable?
1. If this will become configurable, we can wait new version and then configure it not to add the object in a constructor. 
2. If this will not be configurable but will stay like this, we need either to edit the template manually and add changed template to every model in our code or to change all the code(almost impossible)

Thanks in advance for the answer.

**Comment by mciprijanovic** [comment]
Compile bug is corrected in nightly build.

**Comment by msawczyn** [comment]
> If this will not be configurable but will stay like this, we need either to edit the template manually and add changed template to every model in our code or to change all the code(almost impossible)

That code generation pattern is the more proper thing to do; changing it would cause significant ripples in many thousands of other projects. But, of course, the ability to add the .ttinclude to your project and override the code that it generates is one of the defining features of the designer tool, and I would heartily recommend doing that. Going back in the git history, constructors have been generating that way since at least v3 (when the templates were refactored), and for some time before that.

Thanks for the confirmation on 3.0.6. It'll be published as live shortly.
