### ISSUE TITLE
Table schemas are not being used

### ISSUE THREAD

**Issue by bapowell** [msawczyn/EFDesigner#289]
Everywhere in generated code, including migration scripts, instead of the schema name itself (as entered in the Entity's "Database Schema" property in the diagram) being inserted into the table definition, this is what's showing up:
 
"{modelClass.DatabaseSchema}"

**Comment by msawczyn** [comment]
Thanks for the report.

Darn dollar signs 🤦

**Comment by msawczyn** [comment]
Released in v3.0.7
