### ISSUE TITLE
Replace log4net with Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by MagicAndre1981** [msawczyn/EFDesigner#290]
Consider to replace log4net with [Microsoft.Extensions.Logging](https://blog.stephencleary.com/2018/06/microsoft-extensions-logging-part-2-types.html) and allow [switching logging provider via config](https://stackoverflow.com/a/67022463/1466046).

I would like to use [EventSource Logging](https://docs.microsoft.com/is-is/dotnet/api/microsoft.extensions.logging.eventsourceloggerfactoryextensions.addeventsourcelogger?view=dotnet-plat-ext-5.0)

log4net uses some old dependencies that likely trigger [my exception events ](https://github.com/msawczyn/EFDesigner/issues/283#issuecomment-849580684).

**Comment by msawczyn** [comment]
log4net is used only in the assembly parser utilities, not the designer. There are currently no plans to change that.
