### ISSUE TITLE
Designer not shown

### ISSUE THREAD

**Issue by giancarlomelis** [msawczyn/EFDesigner#292]
Hello!
After creating the .efmodel file and open it, Visual Studio shows the xml content, but not the designer:

![issue_pic](https://user-images.githubusercontent.com/18438837/120010536-8c73a980-bfdd-11eb-8f5c-422816a9112a.JPG)

Microsoft Visual Studio Community 2019 Version 16.10.0

What can I do?

**Comment by msawczyn** [comment]
One other user reported this issue, and it appears to be a problem between the designer and some other extension that you may have installed. Could you please post a copy of your Visual Studio log file? That may give a clue as to what's happening.

**Comment by giancarlomelis** [comment]
Thank you.
Which log would you like specifically?

**Comment by msawczyn** [comment]
I'm after the IDE's log (https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2019). If you haven't ever created one of those, it can be quite long. 🤕

**Comment by giancarlomelis** [comment]
Hi.
I've attached a log

[VSLog.log](https://github.com/msawczyn/EFDesigner/files/6570306/VSLog.log)

**Comment by giancarlomelis** [comment]
maybe this is the point?

`  <entry>
    <record>2979</record>
    <time>2021/05/31 15:39:25.515</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [EFModelPackage]Source: &apos;System.ComponentModel.Composition&apos; Description: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.&#x000D;&#x000A;&#x000D;&#x000A;1) No exports were found that match the constraint: &#x000A;&#x0009;ContractName&#x0009;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&#x000A;&#x0009;RequiredTypeIdentity&#x0009;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&#x000D;&#x000A;&#x000D;&#x000A;Resulting in: Cannot set import &apos;Microsoft.VisualStudio.Modeling.Shell.ExtensionEnablement.CommandExtensionRegistrar.mefImportedLogger (ContractName=&quot;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&quot;)&apos; on part &apos;Sawczyn.EFDesigner.EFModel.ExtensionEnablement.EFModelCommandExtensionRegistrar&apos;.&#x000D;&#x000A;Element: Microsoft.VisualStudio.Modeling.Shell.ExtensionEnablement.CommandExtensionRegistrar.mefImportedLogger (ContractName=&quot;Microsoft.VisualStudio.Modeling.ExtensionEnablement.IExtensibilityLogger&quot;) --&gt;  Sawczyn.EFDesigner.EFModel.ExtensionEnablement.EFModelCommandExtensionRegistrar&#x000D;&#x000A;&#x000D;&#x000A;</description>
    <guid>{56BBE1BA-AAEE-4883-848F-E3C8656F8DB2}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>`

**Comment by msawczyn** [comment]
Thanks for providing that; it gave a lot of good information. 

It appears the error is stemming from the MEF (meta-extensibility framework) subsystem in Visual Studio. I did some searching for those kinds of errors and they appear sporadically in reports for various MEF-enabled extensions, even for shipping parts of Visual Studio that are MEF-based (note that the designer contains MEF hooks in it).

There are a number of different solutions that have been given, from repairing Visual Studio and rebooting, to waiting for an update. It appears to be very hit-and-miss as to what fixes it at any given time, which tells me there are different root causes for the same behavior.

I'd suggest starting with clearing the MEF component cache. [Mads has an extension that can help with that](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache#:~:text=The%20Visual%20Studio%20component%20cache,location%20of%20the%20cache%20directory), or you can do it manually (info on that is on the Marketplace page linked above. If that doesn't work, you may have to do a repair, but that's a fairly long process so I wouldn't go there first.

**Comment by giancarlomelis** [comment]
Hello.
Thanks for the reply.
Unfortunately neither solution worked.
Even after Visual Studio restore the model is not shown.
Unfortunately I think I will have to give up.

**Comment by msawczyn** [comment]
Understandable. Thanks for trying, and I'm sorry I couldn't have been more help.
