### ISSUE TITLE
Added Pull Request.  Comments and Questions.

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#296]
Just added a pull request to fix some MEF limitations and add some menus.  I have one area that I am not sure about in the pull request.  I added a menu item to the context menu for a diagram that allows the user to add an entity where they mouse down to open the menu.  I kind of feel like there should be an 'Add' sub menu with all the appropriate items on it depending on where you click, rather than the 'Add Entity' menu item.  If you agree, I will write it and do an additional pull request.

Please let me know,
Daniel

**Comment by msawczyn** [comment]
Hi Daniel,

Thanks for the PR. It'll take me a bit to go through this, so please don't think I'm ignoring it. <grin>

-- Michael

**Comment by dcastenholz** [comment]
Let me know if you would like me to flesh out an 'Add' menu.  Looks like I may have a window to do it.

**Comment by msawczyn** [comment]
Merged
