### ISSUE TITLE
Code generation checks for IsNullOrEmpty on string parameters in class constructor with allowed zero length.

### ISSUE THREAD

**Issue by Kalle4242** [msawczyn/EFDesigner#300]
Hello,
in the model designer I defined a required string property for an entity. I left out a defined value for the "Min Length" property property. An entered "0" was automatically changed back to empty value.
The constructor for the associated class in the generated code checks for IsNullOrEmpty() on the associated string parameter in the constructor call. 
I would expect to check only on is null condition. It 's not possible now to hand over over an empty string.

I think, I use the latest version (3.0.6.1).

**Comment by msawczyn** [comment]
That's by design. To get what you're after, make the property optional, but add a default as an empty string in the partial for the DbContext (implementing the OnModelCreatedImpl partial method).
