### ISSUE TITLE
How can I use an existing DBContext with the Designer

### ISSUE THREAD

**Issue by DBrennanMarine** [msawczyn/EFDesigner#305]
Hi,
I have a data access .Net Core project that already has a DBContext class with all my entities. When I add the designer to this project it doesn't find my existing DBContext and the entities in it. What might I be doing wrong?
Thanks,
Dave.

**Comment by msawczyn** [comment]
You're able to drop a compiled assembly that contains a DbContext on the design surface and it should consume it to populate the designer. You can also add source files for the entities you want included, but there is more information in the assembly, so I'd recommend that.

**Comment by DBrennanMarine** [comment]
> You're able to drop a compiled assembly that contains a DbContext on the design surface and it should consume it to populate the designer. You can also add source files for the entities you want included, but there is more information in the assembly, so I'd recommend that.

Thanks for getting back to me, but I want to add the designer to my current project and use the DBContext class that is already there, as there's a lot of code already using this DBContext class. Is this possible?

**Comment by msawczyn** [comment]
The designer's job is to help create the code for using Entity Framework. I sense that you're just wanting to diagram things? If so, you could import as mentioned above and then just not generate. But, if you do generate the code, it'll follow the style and convention the designer imposes.

That being said, you can always change that style and convention by editing the T4 templates that generates the code. 

Integrating customizations that are already in an existing project is certainly possible, but you'll want to evaluate the amount of work you'll have to put in just to get the codebase to parity with your current functionality before you start saving time and reducing bugs by using the designer. IMHO it's usually worth it, but every project is different.
