### ISSUE TITLE
.Net6 support

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner#306]
Hi @msawczyn , @michael-sawczyn ,

How are you ? Hope you are feeling better.
When is the next release planned on your roadmap ? 

.Net 6 is releasing in Nov '21.
Will there be a EFDesigner release coming out that will support / work with .Net 6 ?

Your input will be appreciated.
Thank you

**Comment by msawczyn** [comment]
It's on the roadmap, but not a high priority. The generated code will run in a .NET 6 environment, so updating it to use new features would be strictly cosmetic.
