### ISSUE TITLE
Feature Request - When renaming tables/columns add annotations so Add-Migration catches the rename

### ISSUE THREAD

**Issue by Falthazar** [msawczyn/EFDesigner#31]
This is probably a very large ask, but I just renamed a table and some fields in the designer. When I went to Add-Migration, it dropped/created a new table instead of renaming.
According to this: https://stackoverflow.com/questions/49799627/rename-a-foreign-key-in-entity-framework-core-without-dropping-data/49802766#49802766

The way to do it is add annotations first, add the migration, and then rename the properties.

Thoughts? It isn't too hard to manually edit the `Up` method of the migration myself, but I figure if someone does a lot of changes, or has a large database, it could be useful.

**Comment by msawczyn** [comment]
Good thought, but that crosses the scope line where the designer needs to stop. We'll generate the runtime code, but we don't (and really shouldn't) do anything concerning the migrations. Unfortunately, the approach you mentioned requires the add-migration command to run, and that's a line I really don't want to cross.

Hopefully the migration algorithm gets smarter in the future and can detect that kind of thing on its own.

Thanks for the suggestion, though! I'll bet many will see that StackOverflow link for the first time here, so it's an excellent addition to the knowledge base.
