### ISSUE TITLE
"Add -> Property" context menu entry missing, cannot add properties to entities

### ISSUE THREAD

**Issue by tarockx** [msawczyn/EFDesigner#311]
Hello

It's my first time using this tool, so maybe I'm missing something completely obvious, but I cannot figure out how to add a new property to an entity.

According to the documentation, you're supposed to right click on the entity and select "add -> property". However, as you can see from the screenshot below, there is no "add" context menu entry when I right click the entity:
![image](https://user-images.githubusercontent.com/10919460/154244615-bad819db-0f30-401e-b260-c5bba7771568.png)

Is this a bug or am I doing something wrong?
I'm using Visual Studio 2022 and the latest version of the extension (downloaded yesterday from the marketplace)

**Comment by Opzet** [comment]
Hi, there are two click regions, try clicking lower in properties, rather than header
Reach out anytime :)
david@digitalgeo.com.au

**Comment by tarockx** [comment]
> Hi, there are two click regions, try clicking lower in properties, rather than header Reach out anytime :) [david@digitalgeo.com.au](mailto:david@digitalgeo.com.au)

Thanks, but apparently I'm on the wrong repository. There is a separate one for the version of the extension that targets VS 2022, and this bug has already been reported there. I'm closing this, since it doesn't affect this version of the extension.
