### ISSUE TITLE
No way to import

### ISSUE THREAD

**Issue by aliegm** [msawczyn/EFDesigner#315]
Trying to import but when doing drag and drop (assembly or source file) to the designer, a "not permitted" icon always appears, 
Windows 11, VS 2022, VS 2019, the last version of the plugin in both cases. Do I am missing something?

**Comment by msawczyn** [comment]
There were some issues with that feature in a prior designer version; please try the most current (4.2.0) and let me know what you find.

**Comment by msawczyn** [comment]
Please reopen this in https://github.com/msawczyn/EFDesigner2022 if you continue to have issues with the latest builds.
