### ISSUE TITLE
Output directories cannot be changed anymore?

### ISSUE THREAD

**Issue by ddewaleffe** [msawczyn/EFDesigner#32]
Having an issue with latest version (updated yesterday  in my VS2017- 15.8.9):
Cannot modify output directories in the properties window:
![image](https://user-images.githubusercontent.com/1861106/48054765-469c2f00-e1ae-11e8-9509-b255862b1524.png)
The fields seem to be read-only and the Combo shows Properties but I cannot change the values....
 Is this just me?

Any idea?

**Comment by msawczyn** [comment]
Do you have any directories in your project? Other than `Properties`, that is.

**Comment by ddewaleffe** [comment]
Ah! Indeed... I need to create the folders first, then they show up in the
combo...

Maybe a note should be added somewhere in the [excellent, btw]
documentation you provide to tell users about that...

While at it, I think it would be easier to not miss one if the folder
properties were all grouped in the tab, as in a specific category
"Generated code folders" or by renaming those properties so they appear all
together in the list...
