### ISSUE TITLE
How add /drag an existing model or entity to design surface 

### ISSUE THREAD

**Issue by papyr** [msawczyn/EFDesigner#320]
Hello this is great I was wondering if you could show or consider allowing us to drag an entity or a model under the designer surface.

I have over 60 different models and it would be nice to pull those into the designer surface so I can easily build a DB contacts in your tool

Can you share some pointers or guidance on how I can modify the designer to let me drag the entities onto the designer surface surface to add/ build a dbContext

**Comment by msawczyn** [comment]
Please see my reply to a similar question at https://github.com/msawczyn/EFDesigner2022/issues/27
