### ISSUE TITLE
VS Crash on multiplicity changes

### ISSUE THREAD

**Issue by ddewaleffe** [msawczyn/EFDesigner#34]
Trying to modify multiplicity of a *->1 relation, VS crashes and restarts...
This happens when trying to open the combo with (expected) other possible values.
Will try to have a simple case and/or vs logs...

**Comment by msawczyn** [comment]
Logs would be great. I've never seen that happen, so would love to be able to track down a case where it does.

**Comment by msawczyn** [comment]
Closing this and tracking on #38
