### ISSUE TITLE
Concurrency mode: optimistic auto generated Timestamp property

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#35]
2 separate, yet related bugs:

1) When Concurrency is set to optimistic, and no property is marked as "Is Concurrency Token", the extension automatically creates a working Timestamp property, but the extension throws an error saying: "Entity1: Should have 1 concurrency properties but has 0".

2) If you add a property and then mark it as "Is Concurrency Token" = True, the generated property has [Required] on it which causes validation errors on save.  The UI does not allow you to change the Required = True setting.

**Comment by msawczyn** [comment]
That'll be fixed in the next version. Thanks for pointing it out.

**Comment by msawczyn** [comment]
This was a tricky one, philosophically, to deal with. In the best of all worlds, the designer and the code generation are separate. Yet the designer should know that the concurrency property will be automatically generated and not give the error. While not the best of all solutions, I've removed the error message, and that change is available in v1.2.6.18.

**Comment by msawczyn** [comment]
Closing since fix is now released
