### ISSUE TITLE
VS2017 Crash

### ISSUE THREAD

**Issue by dcastenholz** [msawczyn/EFDesigner#38]
Created a simple model with 2 entities and a 1 to many association.  Selecting either entity and then selecting the Association Sources (or Targets) entry and then clicking on the Properties window dropdown for 'End2 Multiplicity' (which is currently set to 'ZeroMany') causes VS2017 to crash.

**Comment by dcastenholz** [comment]
Just realized that this is a duplicate of #34.

**Comment by msawczyn** [comment]
Can you make it happen again and upload a VS log? I can't replicate it. :-(

**Comment by dcastenholz** [comment]
Didn't get much, but it does tell where the exception is generated.  

```
<entry>
    <record>644</record>
    <time>2018/11/28 21:13:13.500</time>
    <type>Information</type>
    <source>ExtensionCrashNotification</source>
    <description>c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\e3baosf2.zpy\Sawczyn.EFDesigner.EFModel.Dsl.dll!Sawczyn.EFDesigner.EFModel.TargetMultiplicityTypeConverter.GetStandardValues</description>
  </entry>
```

**Comment by msawczyn** [comment]
Found the problem and will get it fixed quite soon. 

The workaround is to make sure the association line has focus rather than the class. 

Thanks for this info!

**Comment by ddewaleffe** [comment]
I did try v1.2.6.19 on the multiplicity change that was causing a crash. The fix appears to work.

**Comment by msawczyn** [comment]
Super. I'll close the issue and release that build. Thanks!
