### ISSUE TITLE
TPH 

### ISSUE THREAD

**Issue by weedkiller** [msawczyn/EFDesigner#39]
Hi it would be nice to have table splits and table per hierarchy support

**Comment by msawczyn** [comment]
Table per hierarchy is there, and table splitting is on the TODO list. But no guarantees when it'll be implemented. It's a tad tricky for the tooling. :-)

**Comment by weedkiller** [comment]
Your designer is much nicer to use, just showing people how to access the features, I didnt know it was there.

More importantly, I dont know how to implement these correctly, so designer would be agreat help

**Comment by msawczyn** [comment]
Thanks for the kind words! Feel free to leave a review in the Marketplace ... that helps a lot. Cheers!
