### ISSUE TITLE
Support for complex types

### ISSUE THREAD

**Issue by ddewaleffe** [msawczyn/EFDesigner#41]
It seems not possible (yet?) to add such cases in the designer. 
One can add the first one but validation fails because of a missing Id property in the inheritance chain ... But I do not want one...
class Pos {
    double x; double y;
}
Then of course I cannot add a property of type Pos since the type is not recognized...
class Foo {
   int Id;
   string Name;
   Pos Where;
}

Is this something you exclude from the tool or just not here yet?

Thanks,

**Comment by msawczyn** [comment]
It's there. In the designer, they're termed "[Dependent types](https://msawczyn.github.io/EFDesigner/Entities.html)". That's only because EF6 and EFCore have different names for them - complex vs. owned. :-(
