### ISSUE TITLE
Properties generating isUnicode(...) / varchar vs. nvarchar

### ISSUE THREAD

**Issue by johnhenley** [msawczyn/EFDesigner#42]
wanted to get some guidance on best approach for handing ANSI / varchar vs. Unicode / nvarchar for property to column mappings. Best I can determine is to specify [Column(TypeName="varchar")] or [Column(TypeName="nvarchar")] as a custom attribute in the property. Is there a more elegant way to do this?

**Comment by msawczyn** [comment]
Best for that would be the Column Type property. It's normally set to `default`, which would be `nvarchar` for a `string`, but you can change it to `varchar` and that will cause migrations to generate `unicode: false` in the migration.

That being said, that featue as a bug in 1.2.6.20. It's fixed in the most current version, 1.2.6.21.

**Comment by johnhenley** [comment]
That is great---thanks!
Any chance you could add a “isUnicode” default option at either the model or entity level to avoid having to do it for each and every string property?

**Comment by msawczyn** [comment]
I see where you're going, but that a bit too focused and I'd rather do something more general. I've got a property search in the works that I think fits this bill. 

It would let you search for different aspects of a class, property, enum, enum value, or association and would highlight them all. So, for example, if you searched for a property with type == `string`, all such properties would be selected. The Visual Studio property editor, then, would propagate any change you make to each property that's selected. You could, for example, set the `Column Type` to whatever value you wanted, all in one go.

Can't make a promise as to when that will release, but it is on the list.

**Comment by msawczyn** [comment]
Closing due to age
