### ISSUE TITLE
Error in tt files

### ISSUE THREAD

**Issue by LucaGabi** [msawczyn/EFDesigner#45]
![image](https://user-images.githubusercontent.com/37976898/50847953-91d3e900-137b-11e9-917d-d08f0a1249a7.png)

This is present:
<#@ template inherits="Microsoft.VisualStudio.TextTemplating.VSHost.ModelingTextTransformation" debug="true"
             hostSpecific="true" language="C#" compilerOptions="/langversion:latest"#>

**Comment by msawczyn** [comment]
Yes, it is. What seems to be the problem?

**Comment by LucaGabi** [comment]
It dose not use correct C# compiler, maybe ? It marks null-safety operator as responsible for the error, if deleted the red marker goes away .. I don't understand why ..

**Comment by msawczyn** [comment]
I've seen the same thing ... it's an artifact of the editor. The T4 compiler is fine with the syntax the way the project is set up and handles it correctly. It's just intellisense that's having an issue.
