### ISSUE TITLE
Generate Enum attribute

### ISSUE THREAD

**Issue by ngvanmy** [msawczyn/EFDesigner#47]
How I can generate enum with Annotation [Display]? eg:

public enum Salary
{
    [Display(Name="Paid Monthly")]
    PaidMonthly = 1,
    PaidYearly = 2
}

**Comment by msawczyn** [comment]
Starting with v1.2.6.20 you can set the _Display Text_ property on the enumeration value to add the DisplayAttribute to the generated code. For more detailed customization, you can set the _Custom Attribute_ property.

Hope that helps.
