### ISSUE TITLE
.HasForeignKey in EF core 2.2 does not work

### ISSUE THREAD

**Issue by philipbawn** [msawczyn/EFDesigner#49]
EFDesigner only claims compatibility with "Entity Framework Core 2.0 and 2.1" so maybe this shouldn't be an issue-- however I have been using EF Core 2.2 with EFDesigner release 1.2.6.21 and it was fine. Now with EFDesigner 1.2.6.23 my .generated context has .HasForeignKey in it, my program won't run, (has a problem in OnModelCreating). A quick google suggests also that EF core 2.2 has one or more breaking changes in the fluent API with .HasForeignKey vs EF core 2.1
![error1](https://user-images.githubusercontent.com/10352261/51795502-253d5480-2199-11e9-845a-9bf65199c496.PNG)

**Comment by msawczyn** [comment]
Hi Philip,

As you pointed out, there hasn't yet been any testing with 2.2, but that's on the list of things-to-do. But the problem you point out is a 2.2 bug, according to https://github.com/aspnet/EntityFrameworkCore/issues/14158

Based on the discussion in that thread, it's possible that code generation can handle the problem. I'll look into that.

Thanks for bringing it up.
