### ISSUE TITLE
Inheritance Strategy

### ISSUE THREAD

**Issue by peter-davies-auticon** [msawczyn/EFDesigner#56]
i have a dot net core project and can't find the Inheritance Strategy property
is this not supported in dot net core?

**Comment by msawczyn** [comment]
Per https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance, only the table-per-hierarchy (TPH) pattern is implemented in EF Core, so the inheritance strategy property of the DBContext isn't available when using that technology. As EF Core evolves, it will be added back and will generate code appropriate to the choice picked in the model.

**Comment by peter-davies-auticon** [comment]
thanks for that. great addin. many thanks for the work you've done.
if there's anything i can help with feel free to ask,as i'm between jobs right now so time on my hands
which is why i've been messing about with stuff like this https://random-explorations.herokuapp.com/juliagif

**Comment by msawczyn** [comment]
Closed due to age
