### ISSUE TITLE
Issue using with EF Core

### ISSUE THREAD

**Issue by brian-connelly-carvana** [msawczyn/EFDesigner#6]
I'm having an issue using it with EF Core.
I created a simple model with 5 tables, but the generated code is making calls that don't exist in Core:
modelBuilder.HasDefaultSchema(..)
EntityTypeBuilder<..>.ToTable(...)
etc.

Entity Framework Version is set to EFCore,
and the Nuget for Microsoft.EntityFrameworkCore(2.0.2)has been added to the class library project, which is .NET Core 2.0 project.

-BCC

**Comment by michael-sawczyn** [comment]
Thanks for the report. I created a new sample project using .NET Core and EF Core, both v2.0.2, and the code looks good and compiles cleanly, at least on my side. 

The two methods you mentioned should be present. `ModelBuilder.HasDefaultSchema` is in `Microsoft.EntityFrameworkCore.Relational`, as is `RelationalEntityTypeBuilderExtensions.ToTable`. 

Could it be that you didn't add the assembly for the target database, which would, as its dependency, bring in `Microsoft.EntityFrameworkCore.Relational`? For example, if you're targeting SqlServer, you'll want to bring in `Microsoft.EntityFrameworkCore.SqlServer`.

**Comment by msawczyn** [comment]
Thanks for the report. I created a new sample project using .NET Core and EF Core, both v2.0.2, and the code looks good and compiles cleanly, at least on my side. 

The two methods you mentioned should be present. `ModelBuilder.HasDefaultSchema` is in `Microsoft.EntityFrameworkCore.Relational`, as is `RelationalEntityTypeBuilderExtensions.ToTable`. 

Could it be that you didn't add the assembly for the target database, which would, as its dependency, bring in `Microsoft.EntityFrameworkCore.Relational`? For example, if you're targeting SqlServer, you'll want to bring in `Microsoft.EntityFrameworkCore.SqlServer`.
