### ISSUE TITLE
One-to-one seems to generate incorrect code

### ISSUE THREAD

**Issue by rlarik** [msawczyn/EFDesigner#60]
When generating code for a one-to-one relationship like here:

![1to1](https://user-images.githubusercontent.com/9824174/54487764-e0c95d80-4899-11e9-8b5b-895734959c5e.png)

After trying to create a new migration, I get the following error:

> You are configuring a relationship between 'User' and 'Authentication' but have specified a foreign key on 'Authentication_Id'. The foreign key must be defined on a type that is part of the relationship.

After manually adding a property `Authentication_Id` to the `User` entity and changing the fluent entry to
`.HasForeignKey<User>(x => x.Authentication_Id)` it works fine.
Adding the property manually is not an issue as this can be added using the diagram. Changing the fluent API entry will be a hassle as this is overwritten every time I generate the code.

**Comment by msawczyn** [comment]
Thanks for the report; I'll dig into that. Question: were you generating for EF6 or EFCore?

**Comment by rlarik** [comment]
For EFCore, my bad!

**Comment by Tristan-gu** [comment]
Hi @msawczyn ,

For information, I have the same issue too with EFCore.

**Comment by msawczyn** [comment]
I'm having difficulty reproducing this. This simple relationship works when I give it a try. Could one of you please post an efmodel file that has this problem? It would be much easier to review.

Thanks.

**Comment by Tristan-gu** [comment]
Hi,
I have made a little test project to reproduce this.
You can find it in my .NetStandard attached.

When I instanciate my DBContext, and call database.ensureCreated(), I have the error below:
![image](https://user-images.githubusercontent.com/41323690/55714255-a06d8300-59f2-11e9-8654-9fdb3240dad0.png)

Hope this will help

[TestEFCoreLib.zip](https://github.com/msawczyn/EFDesigner/files/3053621/TestEFCoreLib.zip)

**Comment by msawczyn** [comment]
Thanks. Will get to this soonest.

**Comment by msawczyn** [comment]
We've made quite a few enhancements to EFCore code generation in 1.2.7, and one of them seems to have made this problem vanish.

**Comment by msawczyn** [comment]
1.2.7 pre-release is in the releases. Could you take a peek and see if this resolves your issue? Thanks!

**Comment by Tristan-gu** [comment]
For me, the generation and execution are OK

**Comment by msawczyn** [comment]
Fixed and released in 1.2.7.1. Closing issue.
