### ISSUE TITLE
EFModel Error in VS 2019

### ISSUE THREAD

**Issue by Tristan-gu** [msawczyn/EFDesigner#61]
Hi,

I'm trying to use your extension with Visual Studio 2019 (Enterprise release).
But, in my .NetStandard Library, when I add a item 'EFDesigner' to my library, when I double-click on my EFModel1.efmodel file, I have this error.
![image](https://user-images.githubusercontent.com/41323690/55479373-3c2b7780-561e-11e9-83a9-dcc24ed1494d.png)

I d'ont know why I have this error, can you please help me ?

Another questions, what is the minimum requirement to use it inside VS ?
I have installed those below
![image](https://user-images.githubusercontent.com/41323690/55479517-89a7e480-561e-11e9-89cb-3ed8ebf12279.png)

Am I missing something ?
Thank you

**Comment by msawczyn** [comment]
We're not quite VS2019-ready. That should be in a day or so, assuming I can get the time to work through the changes and test it properly. Stay tuned!

**Comment by Tristan-gu** [comment]
ok thank you, I will wait

**Comment by msawczyn** [comment]
1.2.7 pre-release is in the releases. Could you take a peek and see if this resolves your issue? Thanks!

**Comment by Tristan-gu** [comment]
with the Modeling SDK installed, I don't have this issue, but have the same issue like here (#66 )

**Comment by msawczyn** [comment]
Yes, that is a known problem. You don't need to have the Modeling SDK installed to use the extension, but there is a known issue with the version 16 Modeling SDK libraries (that load in the same appdomain as Visual Studio 2019) where projects using the new project format throw exceptions.

I'm trying to figure out how to work around this but, if I can't, it'll be up to Microsoft to produce the fix. DSLs are now effectively broken when using the new project format -- which is effectively all .NET Core and .NET Standard projects.

**Comment by msawczyn** [comment]
Fixed and released in 1.2.7.1 (except for the new project format problems, but that's really a separate issue). Closing this issue.
