### ISSUE TITLE
EFCore indexed column not generated and support for multi column indexing ?

### ISSUE THREAD

**Issue by Tristan-gu** [msawczyn/EFDesigner#62]
Hi,
Waiting for the 2019 relase (#61 ), I'm trying your extension in VS 2017 and your extension is very useful and nice.

But, I think there is a bug in EFCore model: if your set a non Identity column do "indexed", there is absolutely no "hasIndex" generated in the final context.
I don't understand because it's seems to be developed in this [source](https://github.com/msawczyn/EFDesigner/blob/master/src/DslPackage/TextTemplates/EFCoreDesigner.ttinclude). (line 305).

And, another question, when I saw the code below, I wonder how to generate a multi-column index in EFCore model ?  Like this : 
`modelBuilder.Entity<Item>()HasIndex((Item b) => new { b.column1, b.column2, b.column3 });`

Is it planned ?

**Comment by msawczyn** [comment]
Multi column indices are supported. That should be in the documentation (if not, I'll make sure it gets added) but I'm not in front of a pc right now so couldn't tell you exactly where to look. I'll try to find that for you shortly.

Index configuration is also available, but to be honest, I've been deep into an ef6 project for quite a while and haven't looked at the efcore T4 for some time. That's about to change. I'll get back to you on this asap.

**Comment by msawczyn** [comment]
We've reworked a lot of things in EFCore for 1.2.7, and have tests validating that multicolumn indexes are good (at least in that version) for EFCore. Can't say they weren't broken in 1.2.6.x ... but the next release is imminent, so this will be fixed.

**Comment by msawczyn** [comment]
1.2.7 pre-release is in the releases. Could you take a peek and see if this resolves your issue? Thanks!

**Comment by msawczyn** [comment]
Ah, I see what you're after now. Hmm. Currently, you can't. And you should. 

I'll see what can be done.

**Comment by msawczyn** [comment]
Deprioritizing this, since indices can be added manually.
