### ISSUE TITLE
Defining ColumnType causes error in generated DBContext

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#64]
When a ColumnType is specified on a property, then it is generated twice in the DBContext.

![28-12-_2018_13-03-38](https://user-images.githubusercontent.com/49527703/55968021-927e6300-5c7b-11e9-8a8c-468289a4e20f.jpg)
[EF Core 2.2 and EF Visual Editor 1.2.6.25]

**Comment by msawczyn** [comment]
Fixed in 1.2.7

**Comment by msawczyn** [comment]
1.2.7 pre-release is in the releases. Could you take a peek and see if this resolves your issue? Thanks!

**Comment by msawczyn** [comment]
Fixed and released in 1.2.7.1. Closing issue.
