### ISSUE TITLE
Impossible to affect Enum Type for a property

### ISSUE THREAD

**Issue by Tristan-gu** [msawczyn/EFDesigner#69]
When I want to modify the "Entity1.test" property type to an enum, I have this error.

![image](https://user-images.githubusercontent.com/41323690/56305893-77ab6300-6141-11e9-84b1-570a96c60662.png)

![image](https://user-images.githubusercontent.com/41323690/56305856-5c405800-6141-11e9-95e4-48f893774822.png)

**Comment by msawczyn** [comment]
Great catch. Thanks!

**Comment by msawczyn** [comment]
Fixed and released in 1.2.7.1. Closing issue.
