### ISSUE TITLE
Integration w/ Owin or Asp Identity

### ISSUE THREAD

**Issue by ensemblebd** [msawczyn/EFDesigner#7]
I did read the excerpt detailing that this is not meant to import existing models, and that makes perfect sense.

But configuring asp.net and owin is a significant undertaking, so I'm curious as to an alternative to use with this system?

Perhaps an "interface" between the two, like a table with nothing but foreign keys for UserId, Group, Role, etc, as a layer on top of owin, with which my application-models designed in EFDesigner would interact?
I'd still have to customize the linkages manually in the code, so the model wouldn't perfectly reflect (visually speaking) what is actually taking place.. Adds a bit of overhead too. But maybe that's the answer?

Just curious if anyone has stepped through similar and has any suggestions. Thank you!

**Comment by ensemblebd** [comment]
It took a lot of effort, but this is easily achievable using: 
https://msawczyn.github.io/EFDesigner/Properties.html#adding-properties-via-code-custom-property-syntax
And IL overload for `OnModelCreatedImpl`. 

The only thing that has been impossible to solve, is that it creates it's own foreign keys. The [tt] templates are generating a .Map() property to associate virtual entity/collections. 
It sounds like the only way to solve that would be to modify the [tt] templates and somehow add properties to the [link] tools to select from available properties. 

Was curious if that is something on your roadmap for development?

**Comment by michael-sawczyn** [comment]
Hi @ensemblebd. I'm not real clear on what you're trying to do. Can you give me a use case and how you think a visual model will help?

Thanks.

**Comment by ensemblebd** [comment]
No problem, I'll see about getting a repo made up to show the use case. 

Asp.Net Identity , and Owin, are systems that utilize EF6 models to authenticate and manage a stateless user account. It comes out of the box with many bells and whistles regarding security and identity management/integration.

So what I'm trying to achieve: 

1. In the first (original @ top) post, I was trying to use existing EF6 models in the Visual Designer.  I was able to figure that out. It's not perfect, but it works well enough. 
2. In the second post, I am talking about the generated models produced by EFDesigner which have [Links] between [Entities] , which when generated force you to use auto-generated foreign keys. Well that's a problem if I already have my own model with it's predefined foreign key, right? Right.  So was asking if that is on the development roadmap by chance?   Custom-Foreign-Keys. 

The whole reason for using EFDesigner is to make life easier and to help the fresh college graduates understand things easier. But if I can't use the [Link] between entities due to a forced autogenerated foreign key, then there isn't much of a reason to proceed using it. Boxes without links between them are just as understandable as code blocks across several files. 

In all honesty, I'm hitting a needle with a baseball bat, or perhaps visa versa. I try to make things easier on coworkers, but the truth is, they just need to learn to code properly, and put in some effort.

**Comment by msawczyn** [comment]
@ensembled - I see where you're going with this. If I'm not mistaken, you should be able to do what you want without any changes, since you can flag any property as an identity (but currently only one) as long as it's the right type.

Let me work up an example. Shouldn't take too long (unless, of course, my wife had a list of things she needs me to get done tonight :-) ).
