### ISSUE TITLE
One-to-one relation in EFCore

### ISSUE THREAD

**Issue by Tristan-gu** [msawczyn/EFDesigner#71]
Hi,

I'm trying to understand one-to-one relation, and tried this [sample](https://www.entityframeworktutorial.net/efcore/one-to-one-conventions-entity-framework-core.aspx).

I have this model
![image](https://user-images.githubusercontent.com/41323690/56599821-ad47c480-65f7-11e9-9fc7-2fb154ac9bb7.png)

Where Student is the principal item in the model.

And I have this result in my SQLite DB:
![image](https://user-images.githubusercontent.com/41323690/56599970-fe57b880-65f7-11e9-840b-f19017382847.png)

I should have student_Id column in the StudentAddress table isn't it ?

**Comment by Tristan-gu** [comment]
Seems to be a bug in the context generator.
This relation
![image](https://user-images.githubusercontent.com/41323690/56638629-eec78680-666e-11e9-84fc-1c87c36ce108.png)


should be
![image](https://user-images.githubusercontent.com/41323690/56638561-c8a1e680-666e-11e9-9a18-e7525e8422ff.png)

**Comment by msawczyn** [comment]
Spot on - thanks! Fixing for 2.7.2.
