### ISSUE TITLE
Setting to generate context with one single constructor for pooling [FEATURE REQUEST]

### ISSUE THREAD

**Issue by mmarinchenko** [msawczyn/EFDesigner#72]
EF Core supports context poling by calling `AddDbContextPool<>()` instead of `AddDbContext<>()` inside `ConfigureServices()` method. But this requires context to have only one single constructor with options parameter:

`InvalidOperationException: The DbContext of type 'DataContext' cannot be pooled because it does not have a single public constructor accepting a single parameter of type DbContextOptions.`

To workaround this I commented the following lines in local copy of `EFCoreDesigner.ttinclude` file:

`//    Output("/// <inheritdoc />");`
`//    Output($"public {modelRoot.EntityContainerName}() : base()");`
`//    Output("{");`
`//    Output("}");`
`//    NL();`

It would be great to add setting for that in Entity Context section of diagram properties :)

**Comment by mmarinchenko** [comment]
To be honest I don't understand why the context in EF Core might need a default constructor without parameters.

**Comment by msawczyn** [comment]
Now that you mention it, neither do I. I'm removing that, but adding an option to generate a default constructor for the DbContext that defaults to `false`. Something nags at me that I put that there for a reason but, of course, didn't document it at the time so don't remember why now. (https://i.redd.it/hwqj7yx9vm211.jpg)

**Comment by mmarinchenko** [comment]
Thanks for your support!

I tried to test this but something went wrong :(

1.2.7.2 version is not working:
`A processor named 'EFModelDirectiveProcessor' could not be found for the directive named 'EFModel'. The transformation will not be run.  The following Exception was thrown:
System.InvalidCastException: Failed to resolve type for directive processor EFModelDirectiveProcessor.
   at Microsoft.VisualStudio.TextTemplating.VSHost.TextTemplatingService.ResolveDirectiveProcessorFromRegistry(String processorName, OrchestratorPackage orchestratorPackage)
   at Microsoft.VisualStudio.TextTemplating.VSHost.TextTemplatingService.ResolveDirectiveProcessor(String processorName)
   at Microsoft.VisualStudio.TextTemplating.Engine.ProcessCustomDirectives(ITextTemplatingEngineHost host, TemplateProcessingSession session, IEnumerable``1 directivesToBeProcessed)	ClassLibrary1	D:\VSProjects\ClassLibrary1\ClassLibrary1\EFModel1.tt	17`

I reverted to 1.2.7.1 and all is good...

**Comment by msawczyn** [comment]
There was an issue with the build server causing the vsix to have some issues. I've since rebuilt and verified that it runs in VS2017 and VS2019. The new build is posted in the marketplace and here on github with the same version number. Please give that a go, and my apologies for the problems.

**Comment by mmarinchenko** [comment]
Yes, now it's working as expexted. Thank you!

**Comment by rlarik** [comment]
>  something nags at me that I put that there for a reason but, of course, didn't document it at the time so don't remember why now

Generating a migration without a parameterless constructor results in an error:
Unable to create an object of type 'DataContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

Adding the empty constructor back fixes this problem. Where in the docs have you added the information?

**Comment by mmarinchenko** [comment]
@rlarik, thanks for the info!

I forgot about that because I use ASP.NET Core framework :)

In ASP.NET Core scenario both parameterless constructor and OnConfiguring() method are not needed.

**Comment by mmarinchenko** [comment]
So, maybe it would be more appropriate to add a setting regarding the ASP.NET Core framework:
- use `IdentityDbContext` as base class instead of `DbContext` (see original point 3 in issue #53, other two points are not needed actually)
- do not generate parameterless constructor for context class
- do not generate CustomInit() and OnConfiguring() methods for context class

Default value is **false**.

P.S. `EFCoreDesigner.ttinclude` contains code related to Lazy Loading and Inheritance Strategy settings but they are not available for EF Core version of diagram properties :)
