### ISSUE TITLE
Creation of manual Identity Columns

### ISSUE THREAD

**Issue by dermaier089** [msawczyn/EFDesigner#79]
whatever set in the designer on an identity property, the generated code in 

OnModelCreating ->

always sets the DatabaseGeneratedOption to Identity

.HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

**Comment by msawczyn** [comment]
Fixed in 1.3.0.4

**Comment by msawczyn** [comment]
Closing since fix was released.
