### ISSUE TITLE
Default namespaces for artifact types

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#80]
- Accepting user defined model classes as Base Class of an entity: Now only Tables from the Diagram can be added as BaseTable. If multiple Diagramms in an Application exist, there might be one global base table from which all other tables are derrived. 
As Workaround I used the custom Interface property to get the right code generated. But of course then I get validation errors concerning the identity columns etc, because there are no validations or checks of the "custom interface" class. 
- Different Namespaces: At the moment all generated classes are using the same namespace. Would be good, if it is possible to define own (differing) namespaces for Enums, Entities, Structs from the global assigned namespace.

**Comment by mmarinchenko** [comment]
Voted for namespaces!

I would be happy to have separate options at least for DbContext's namespace and Entities' default namespace. Maybe it also would be nice to have something like "Generate namespaces based on directory structure" check)

**Comment by msawczyn** [comment]
I'm a little confused regarding the ability to change namespace on a per-element basis. This has always been a feature.

**Comment by mmarinchenko** [comment]
Per-type of the element, not per-element :) There are 4 properties for output directories on the diagram level at the moment. And namespaces must be managed by hand on per-element basis.

I can separate DbContext class from other elements but for that I have to define DbContext's namespace on a diagram level and then all developers in my team have to change namespace in element's property every time they add new element to diagram. I cannot define a separate namespace just for DbContext class. I also cannot define different (default) namespaces for (all) entities, (all) enums and (all) structs.

**Comment by msawczyn** [comment]
Got it. Good idea. It's on the list now.

**Comment by mmarinchenko** [comment]
Cool!

**Comment by ANM86** [comment]
Just one more thing im thinking concerning the usability and namespaces is that it might be useful to include the namespace of the enums in the entity class. In my case I've a custom attribute which uses an enum value. Now my CustomAttributes string seems to be infinite :-)

It looks like "[MyCustomAttribute(Company.Project.Model.Types.Enums.EnumName.Value)]". In the properties windows (without IntelliSense) this might be a little bit frustrating - to correct the type mistakes after code generation. A smarte way would be to include "using" the namespace =>[MyCustomAttribute(EnumName.Value)]

**Comment by msawczyn** [comment]
Changing the title of this for tracking purposes. First bullet point (transient base class) won't be integrated, so repurposing this issue as second bullet point.

**Comment by ANM86** [comment]
Hmm...could it be that the using directives for the namespaces of the enums are missing?

**Comment by ANM86** [comment]
> Hmm...could it be that the using directives for the namespaces of the enums are missing?

I noticed that now there is a check for enum values in the constructor of the entity class if an enum is used as type for a property.
The check throws an ArgumentOutOfRangeException if the value equals the enum's default value.

There I noticed that the enum's namespace is missing 
Further I'm not sure if it is an good idea to throw the exception if the value is the same as the default value. As far as I could see, this check logic will be included as soon as the property is required.
In my case I explicitly want it to be the same value (because it is value 0 => not NULL). Can I exclude this check by any property? Otherwise I would have to redefine all enum values new. This also means that a Enum never can be value 0 if it used as type for a column property.

**Comment by mmarinchenko** [comment]
One more minor pedantic thing)

Naming style and sort order of new namespace-related settings is slightly different from directory-related ones. This can lead to some confusion when editing values frequently.

P.S. Many thanks for the feature!

**Comment by msawczyn** [comment]
The default value check should not have slipped in -- that was an experimental bit that didn't pan out.

In line 546 of `EFDesigner.ttinclude`, you can remove
```
else
   Output($"if ({requiredAttribute.Name.ToLower()} == default({requiredAttribute.PrimitiveType})) throw new ArgumentOutOfRangeException(nameof({requiredAttribute.Name.ToLower()}));");
```
That change will be made in the next release, which will be Real Soon (since it breaks code).

**Comment by ANM86** [comment]
I already removed the lines, but now it is clear why I couldn't find an appropriate entry in the change log :-)
