### ISSUE TITLE
Issues with EF Core 3.0

### ISSUE THREAD

**Issue by MattEvansA45** [msawczyn/EFDesigner#94]
Hi

I just wondered if the tool was supposed to currently work with .net Core 3.0? (i appreciate it's currently preview) i can't see any option in the dropdown for versions

I'm trying to create a WPF app using EFCore 3.0 however i've got the following errors in the generate DBContext file

![image](https://user-images.githubusercontent.com/41288088/64002839-ee4e6900-cb02-11e9-9b54-7d143ff1f5a5.png)

'ModelBuilder' does not contain a definition for 'HasDefaultSchema' and no accessible extension method 'HasDefaultSchema' accepting a first argument of type 'ModelBuilder' could be found (are you missing a using directive or an assembly reference?)

'EntityTypeBuilder<Connection>' does not contain a definition for 'ToTable' and no accessible extension method 'ToTable' accepting a first argument of type 'EntityTypeBuilder<Connection>' could be found (are you missing a using directive or an assembly reference?)

If i comment out the offending rows and try to do a migration i get the follwoing error
PM> dotnet ef migrations add InitialCreate --project EDW_Creator
Unable to create an object of type 'MetadataModel'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

Many thanks

**Comment by msawczyn** [comment]
No, we haven't made a move yet toward EFCore 3.0. That should start up here shortly, but didn't want to do too much and have it change prior to release. Thanks for asking ... I'm sure more folks are wondering the same thing.
