### ISSUE TITLE
Missing Toolbox

### ISSUE THREAD

**Issue by MattEvansA45** [msawczyn/EFDesigner#95]
I seem to have lost the toolbox when in the designer screen.

I can't for the life of me find how to restore it therefore i can't add any new items or create associations between classes etc

I've tried resetting the toolbox, restarting Visual Studio 2019 (VS 16.2.3) but no luck.

I've even uninstalled and reinstalled extension

Can anyone advise how i can get this back

Many Thanks

**Comment by msawczyn** [comment]
Visual Studio occasionally has problems with its toolbox cache, but that can be cleared and recreated. Please see https://devdept.zendesk.com/hc/en-us/articles/217842718-Resetting-Toolbox-and-Clearing-the-Toolbox-Cache
