### ISSUE TITLE
DSL: Grouping / selection of entities

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#98]
Have you ever thought about grouping of entities or something like that? Just recognized, that my model still growing and growing. So I stumbled about one little thing which would make life easier :-)  Until now i used the coloring to visualize some kind of grouping. So what would be a nice feature, is the possibility to use the select context menu. * Select per Color, per Database scheme or some other kind of grouping criteria, maybe a new entity property or anything like that, would be really nice.

**Comment by msawczyn** [comment]
Interesting suggestion. It can get complicated, since there are so many possibilities to choose from in the selection, but we'll put it on the list and see if it's something that can be implemented cleanly. Thanks!

**Comment by msawczyn** [comment]
If I understand correctly, this functionality is implemented via the multi-diagram feature.

**Comment by ANM86** [comment]
Yes, thank you. I guess the most useful parts are covered with the new multi-diagram feature.
