### ISSUE TITLE
Turn Off Pluralisation of DB object names

### ISSUE THREAD

**Issue by MattEvansA45** [msawczyn/EFDesigner#99]
Hi,
Is it possible to turn off the pluralisation of names of the DB objects created? I can't obviously see any configuration option on the.efmodel screen.

I've found some example code of how this is done (see below) but unsure how this can be implemented for example by creating  a *.custom.cs file for the EFModel.

`        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.RemovePluralizingTableNameConvention();
        }`

`public static class ModelBuilderExtensions
    {
        public static void RemovePluralizingTableNameConvention(this ModelBuilder modelBuilder)
        {
            foreach (IMutableEntityType entity in modelBuilder.Model.GetEntityTypes())
            {
                entity.Relational().TableName = entity.DisplayName();
            }
        }
    }`

**Comment by msawczyn** [comment]
Hi Matt,

When using the designer, the simplest approach is to just null out the pluralizer in the .ttinclude file. In both `EF6Designer.ttinclude` and `EFCoreDesigner.ttinclude` you'll find the line
```
PluralizationService pluralizationService = ModelRoot.PluralizationService;
```
Change that to
```
PluralizationService pluralizationService = null;
```
and the DbSet property name won't be pluralized. You also have, via the designer properties, complete control over the names of both the DbSet and table, so could change those per entity class.

Hope that helps.
